---
title: "Analysis"
author: "Sglatt"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r packages}
if (!require("bootnet")) {install.packages("bootnet"); require("bootnet")}
if (!require("cowplot")) {install.packages("cowplot"); require("cowplot")}
if (!require("dplyr")) {install.packages("dplyr"); require("dplyr")}
if (!require("effectsize")) {install.packages("effectsize"); require("effectsize")} 
if (!require("EGAnet")) {install.packages("EGAnet"); require("EGAnet")} 
if (!require("ggplot2")) {install.packages("ggplot2"); require("ggplot2")}
if (!require("ggpubr")) {install.packages("ggpubr"); require("ggpubr")}
if (!require("ggridges")) {install.packages("ggridges"); require("ggridges")}
if (!require("gridExtra")) {install.packages("gridExtra"); require("gridExtra")}
if (!require("IsingFit")) {install.packages("IsingFit"); require("IsingFit")}
if (!require("Isinglandr")) {install.packages("Isinglandr"); require("Isinglandr")}
if (!require("knitr")) {install.packages("knitr"); require("knitr")}
if (!require("lsr")) {install.packages("lsr"); require("lsr")}
if (!require("psych")) {install.packages("psych"); require("psych")}
if (!require("pwr")) {install.packages("pwr"); require("pwr")}
if (!require("qgraph")) {install.packages("qgraph"); require("qgraph")}
if (!require("RColorBrewer")) {install.packages("RColorBrewer"); require("RColorBrewer")} 
if (!require("rcompanion")) {install.packages("rcompanion"); require("rcompanion")} 
if (!require("readxl")) {install.packages("readxl"); require("readxl")}
if (!require("remotes")) {install.packages("remotes"); require("remotes")}
if (!require("Rmisc")) {install.packages("Rmisc"); require("Rmisc")}
if (!require("rstatix")) {install.packages("rstatix"); require("rstatix")} 
if (!require("sm")) {install.packages("sm"); require("sm")}
if (!require("tidyverse")) {install.packages("tidyverse"); require("tidyverse")}
if (!require("viridis")) {install.packages("viridis"); require("viridis")} 
if (!require("writexl")) {install.packages("writexl"); require("writexl")} 
```

### Current suicide group 

```{r S Isolate variables}
RESST_sui_binary <- dplyr::select(RESST_sim_sui_di, # binary vars
                              R1, 
                              R2, 
                              R3,
                              R4, 
                              R5, 
                              R6,
                              R7, 
                              R8, 
                              R9,
                              R10, 
                              R11, 
                              R12,
                              R13, 
                              R14, 
                              R15,
                              R16, 
                              R17, 
                              R18,
                              R19, 
                              R20, 
                              R21,
                              )

write.csv(RESST_sui_binary, 'Sui_data_output/DF_sui_data_274.csv') # csv with our final dataset

nodeNames = c( "R1_di","R2_di", "R3_di","R4_di", "R5_di", "R6_di","R7_di", "R8_di", "R9_di","R10_di", "R11_di","R12_di","R13_di","R14_di","R15_di","R16_di", "R17_di", "R18_di","R19_di", "R20_di", "R21_di")
```

```{r S Ising model}
RESST_sui_binary_res <- IsingFit(RESST_sui_binary, plot = FALSE) 

sim_sui_base_ising <- qgraph(RESST_sui_binary_res$weiadj,
                     theme = "colorblind",
                     nodeNames = nodeNames,
                     label.norm = "OOO",
                     legend = FALSE,
                     border.width = as.numeric(abs(RESST_sui_binary_res$thresholds)*3),
                     border.color = "purple") #  Node borders show the preference of the  node to be present/absent. > thickness shows lower likelihood to activate.

### get connectivity and threshold objects -  to use these in  (1) case simulations -- equilibrium perturbed -- and (2) phase stability analysis ###

connectivity_resst_sui_sim = RESST_sui_binary_res$weiadj 
thresholds_resst_sui_sim = RESST_sui_binary_res$thresholds 

## save connectivities and thresholds as dataframes and then excel files 
# connectivities

DF_ising_connectivities <- as.data.frame(connectivity_resst_sui_sim)

write.csv(DF_ising_connectivities, 'Sui_data_output/DF_sui_ising_connectivities.csv') # csv with ising model connectivities 
## this saved our connectivies as an excel

# save(DF_ising_connectivities, file="DF_ising_connectivities.Rdata") # Rdata file to directly import to R
## this saved our connectivies as Rdata

# thresholds

DF_ising_thresholds <- as.data.frame(thresholds_resst_sui_sim)

write.csv(DF_ising_thresholds, 'Sui_data_output/DF_sui_ising_thresholds.csv') # excel with ising model feature thresholds
## this saved our thresholds as an excel

# save(DF_ising_thresholds, file="DF_ising_thresholds.Rdata") # Rdata file to directly import to R
## this saved our thresholds as Rdata

# save image of ising model
# pdf("sim_sui_base_ising", width=10, height=10)
# plot(sim_sui_base_ising)
# dev.off()

# view 
DF_ising_connectivities
DF_ising_thresholds
```

```{r S simulate equilibrium}
set.seed(123456)
Ntime = 20000 # 20,000 time points to simulate

Glauber_2(connectivity_resst_sui_sim, thresholds_resst_sui_sim, Ntime, beta = 1.5)
Equilibrium_sui <- output.binary_eq 
Pertubations_sui <- output.binary_pert
stateEQ_sui <- mean(apply(Equilibrium_sui,1,sum)) # mean sum of active symptoms at equilibrium 
statePERT_sui <- mean(apply(Pertubations_sui,1,sum))  # mean sum of active symptoms at with perturbations 

stateEQ_sui_sd <- sd(apply(Equilibrium_sui,1,sum)) # sd of sum of active symptoms at equilibrium 
statePERT_sui_sd <- sd(apply(Pertubations_sui,1,sum)) # sd of sum of active symptoms at with perturbations

stateEQ_sui # 5.04
statePERT_sui # 11.7495
stateEQ_sui_sd  # 3.969833
statePERT_sui_sd  # 6.877086

# make dataframe with total active nodes at equilibrium and with perturbations at all timepoints (20,000)
DF_simulations_sui <- data.frame(Timepoints = 1:Ntime,
                         Equilibrium = apply(Equilibrium_sui,1,sum),
                         Perturbations = apply(Pertubations_sui,1,sum)) 

data.frame(DF_simulations_sui)

summary(DF_simulations_sui) # look at median and interquartile range 
# Timepoints     Equilibrium    Perturbations  
# Min.   :    1   Min.   : 0.00   Min.   : 0.00  
# 1st Qu.: 5001   1st Qu.: 2.00   1st Qu.: 5.00  
# Median :10000   Median : 4.00   Median :13.00  
# Mean   :10000   Mean   : 5.04   Mean   :11.75  
# 3rd Qu.:15000   3rd Qu.: 7.00   3rd Qu.:18.00  
# Max.   :20000   Max.   :20.00   Max.   :21.00  

DF_subset_1_2k <- subset(DF_simulations_sui, Timepoints >= 1000 & Timepoints <= 2000)
summary(DF_subset_1_2k) # doing this for the perturbed response from 1000-20000
# Timepoints    Equilibrium    Perturbations  
# Min.   :1000   Min.   :0.000   Min.   : 0.00  
# 1st Qu.:1250   1st Qu.:2.000   1st Qu.: 6.00  
# Median :1500   Median :3.000   Median :17.00  
# Mean   :1500   Mean   :3.529   Mean   :13.22  
# 3rd Qu.:1750   3rd Qu.:5.000   3rd Qu.:20.00  
# Max.   :2000   Max.   :9.000   Max.   :21.00  
Pertubations_sui_1_2k <- Pertubations_sui[1000:2000, ]
Pertubations_PERT_sui_1_2k_mean <- mean(apply(Pertubations_sui_1_2k,1,sum)) 
Pertubations_PERT_sui_1_2k_sd <- sd(apply(Pertubations_sui_1_2k,1,sum)) 
Pertubations_PERT_sui_1_2k_mean # mean =  13.22378
Pertubations_PERT_sui_1_2k_sd # SD = 7.193739

DF_subset_2_3k <- subset(DF_simulations_sui, Timepoints >= 2000 & Timepoints <= 3000)
summary(DF_subset_2_3k) # look at one period of perturbation. doing this for the perturbed response from 2000-3000
# Timepoints    Equilibrium    Perturbations  
# Min.   :2000   Min.   :0.000   Min.   :10.00  
# 1st Qu.:2250   1st Qu.:1.000   1st Qu.:14.00  
# Median :2500   Median :2.000   Median :15.00  
# Mean   :2500   Mean   :1.823   Mean   :15.51  
# 3rd Qu.:2750   3rd Qu.:3.000   3rd Qu.:17.00  
# Max.   :3000   Max.   :7.000   Max.   :21.00  
Pertubations_sui_2_3k <- Pertubations_sui[2000:3000, ]
Pertubations_PERT_sui_2_3k_mean <- mean(apply(Pertubations_sui_2_3k,1,sum)) 
Pertubations_PERT_sui_2_3k_sd <- sd(apply(Pertubations_sui_2_3k,1,sum)) 
Pertubations_PERT_sui_2_3k_mean # mean = 15.51349 
Pertubations_PERT_sui_2_3k_sd # SD 2.593852

# plot density (active sum density) at equilibrium and with perturbation

# individual plots
ggplot(data = DF_simulations_sui) + geom_density(aes(x=Equilibrium) , fill = "#00AFBB")
ggplot(data = DF_simulations_sui) + geom_density(aes(x=Perturbations) , fill = "#00AFBB")

# combined plot
# change some default settings 
ggplot(data = DF_simulations_sui) +
  geom_density(aes(x = Equilibrium, fill = "Equilibrium"), alpha = 0.5) +
  geom_density(aes(x = Perturbations, fill = "Perturbations"), alpha = 0.5) +
  scale_fill_manual(values = c("#838B8B", "#C1CDCD"), name = "") +
  labs(title = "", 
       x = "Active symptoms over 20,000 timepoints", 
       y = "Density") +
  theme(panel.background = element_rect(fill = "white"),
        panel.grid.major = element_line(color = "grey", linetype = "dashed"),
        panel.grid.minor = element_line(color = "grey", linetype = "dashed"),
        text=element_text(size = 14,  family = "serif"))

## save Rdata/csv dataframes ##

# active node totals at equilibrium and with perturbations
write.csv(DF_simulations_sui, "Sui_data_output/DF_sui_simulations.csv") 
# save(DF_simulations_sui, file="DF_simulations_sui_20k.Rdata")

# raw simulated data at equilibrium (n = 20,000 for 21 variables)
Equilibrium_sui <- as.data.frame(Equilibrium_sui)
write.csv(Equilibrium_sui, "Sui_data_output/DF_sui_equilibrium.csv")
# save(Equilibrium_sui, file ="DF_equilibrium_sui_20k.Rdata")

# raw simulated data with perturbations (n = 20,000 for 21 variables)
Pertubations_sui <- as.data.frame(Pertubations_sui)
write.csv(Pertubations_sui, "Sui_data_output/DF_sui_perturbations.csv")
# save(Pertubations_sui, file="DF_perturbations_sui_20k.Rdata")
```

```{r S simulation plots}
# equilibrium #
ggplot(DF_simulations_sui, # load 
       aes(x = Timepoints, y = Equilibrium)) + 
  geom_line() +
  theme_classic() +
  labs(title = "", 
       x = "Time points",
       y = expression(paste("RESST symptoms - FSA"))) +
  theme(
    plot.title = element_text(size = 14, face="bold", hjust = 0.5),
    axis.title = element_text(size=12, face = "bold"),
    axis.text = element_text(size = 12, face = "bold")) 

hist(DF_simulations_sui$Equilibrium,
     col="black",
     xlim=c(0,21),
     breaks=seq(0,21),
     main="",
     xlab = expression(bold("Symptoms")),
     ylab = expression(bold(paste("RESST symptoms - FSA"))))

# perturbations #
ggplot(DF_simulations_sui, aes(x = Timepoints, y = Perturbations)) + 
  geom_line() +
  theme_classic() +
  geom_vline(xintercept = seq(from = 1000, to = Ntime -1, by=1000), color="pink", 
             size=.7) +
  labs(title = "", 
       x = "Time points",
       y = expression(paste("RESST symptoms - FSA"))) +
  theme(
    plot.title = element_text(size = 14, face="bold", hjust = 0.5),
    axis.title = element_text(size=12, face = "bold"),
    axis.text = element_text(size = 12, face = "bold")) 

# plot perturbed time 2,000 - 3,000 (close up of full)
ggplot(DF_simulations_sui, aes(x = Timepoints, y = Perturbations)) + 
  geom_line() +
  theme_classic() +
  geom_vline(xintercept = seq(from = 1000, to = Ntime -1, by=1000), color="pink", 
             size=.7) +
  labs(title = "", 
       x = "Time points",
       y = expression(paste("RESST symptoms - FSA"))) +
  theme(
    plot.title = element_text(size = 14, face="bold", hjust = 0.5),
    axis.title = element_text(size=12, face = "bold"),
    axis.text = element_text(size = 12, face = "bold")) + scale_x_continuous(limits = c(2000, 3000))

# plot perturbed time 1,000 - 2,000 (cloe up of full)
ggplot(DF_simulations_sui, aes(x = Timepoints, y = Perturbations)) + 
  geom_line() +
  theme_classic() +
  geom_vline(xintercept = seq(from = 1000, to = Ntime -1, by=1000), color="pink", 
             size=.7) +
  labs(title = "", 
       x = "Time points",
       y = expression(paste("RESST symptoms - FSA"))) +
  theme(
    plot.title = element_text(size = 14, face="bold", hjust = 0.5),
    axis.title = element_text(size=12, face = "bold"),
    axis.text = element_text(size = 12, face = "bold")) + scale_x_continuous(limits = c(1000, 2000))

hist(DF_simulations_sui$Perturbations,
     col="black",
     xlim=c(0,21),
     breaks=seq(0,21),
     main="",
     xlab = expression(bold("Symptoms")),
     ylab = expression(bold(paste("RESST symptoms - FSA"))))
```
```{r S system activity preference}
# connectivity_resst_sui_sim = RESST_sui_binary_res$weiadj 
# thresholds_resst__sui_sim = RESST_sui_binary_res$thresholds 

set.seed(123456)
l1 <- make_2d_Isingland(thresholds = RESST_sui_binary_res$thresholds, 
                        weiadj = RESST_sui_binary_res$weiadj, 
                        beta = 1, 
                        transform = TRUE)

plot(l1)
calculate_resilience(l1)
# when the potential value is higher, the system is less stable and tends to move to more stable state. 

# ggsave("./manuscript/original_network_resilience.png", plot(l1) + autolayer(calculate_resilience(l1)), width = 8, height = 6)
```

```{r S simulations INDIVIDUAL item manipulations)}

# we are manipulating each symptom by 2 SD - to prefer to be more present, THEN, run at equilibrium with glaubers dynamics

# I can't get a loop to work without incorporating the previous manipulation in the following one, so just doing them individually 

amount_of_SDs_perturbation = 2

# Manipulate item 1's threshold
manipulated_thresholds_resst_sui_sim1 <- thresholds_resst_sui_sim
manipulated_thresholds_resst_sui_sim1[1] <- manipulated_thresholds_resst_sui_sim1[1] + amount_of_SDs_perturbation * sd(thresholds_resst_sui_sim)
print(manipulated_thresholds_resst_sui_sim1) # .-1.64

# Manipulate item 2's threshold
manipulated_thresholds_resst_sui_sim2 <- thresholds_resst_sui_sim
manipulated_thresholds_resst_sui_sim2[2] <- manipulated_thresholds_resst_sui_sim2[2] + amount_of_SDs_perturbation * sd(thresholds_resst_sui_sim)
print(manipulated_thresholds_resst_sui_sim2) # .70

# Manipulate item 3's threshold
manipulated_thresholds_resst_sui_sim3 <- thresholds_resst_sui_sim
manipulated_thresholds_resst_sui_sim3[3] <- manipulated_thresholds_resst_sui_sim3[3] + amount_of_SDs_perturbation * sd(thresholds_resst_sui_sim)
print(manipulated_thresholds_resst_sui_sim3) # -.55

# Manipulate item 4's threshold
manipulated_thresholds_resst_sui_sim4 <- thresholds_resst_sui_sim
manipulated_thresholds_resst_sui_sim4[4] <- manipulated_thresholds_resst_sui_sim4[4] + amount_of_SDs_perturbation * sd(thresholds_resst_sui_sim)
print(manipulated_thresholds_resst_sui_sim4) # -.11

# Manipulate item 5's threshold
manipulated_thresholds_resst_sui_sim5 <- thresholds_resst_sui_sim
manipulated_thresholds_resst_sui_sim5[5] <- manipulated_thresholds_resst_sui_sim5[5] + amount_of_SDs_perturbation * sd(thresholds_resst_sui_sim)
print(manipulated_thresholds_resst_sui_sim5) # -.84

# Manipulate item 6's threshold
manipulated_thresholds_resst_sui_sim6 <- thresholds_resst_sui_sim
manipulated_thresholds_resst_sui_sim6[6] <- manipulated_thresholds_resst_sui_sim6[6] + amount_of_SDs_perturbation * sd(thresholds_resst_sui_sim)
print(manipulated_thresholds_resst_sui_sim6) # -.009

# Manipulate item 7's threshold
manipulated_thresholds_resst_sui_sim7 <- thresholds_resst_sui_sim
manipulated_thresholds_resst_sui_sim7[7] <- manipulated_thresholds_resst_sui_sim7[7] + amount_of_SDs_perturbation * sd(thresholds_resst_sui_sim)
print(manipulated_thresholds_resst_sui_sim7) # 0.71

# Manipulate item 8's threshold
manipulated_thresholds_resst_sui_sim8 <- thresholds_resst_sui_sim
manipulated_thresholds_resst_sui_sim8[8] <- manipulated_thresholds_resst_sui_sim8[8] + amount_of_SDs_perturbation * sd(thresholds_resst_sui_sim)
print(manipulated_thresholds_resst_sui_sim8) # -1.45

# Manipulate item 9's threshold
manipulated_thresholds_resst_sui_sim9 <- thresholds_resst_sui_sim
manipulated_thresholds_resst_sui_sim9[9] <- manipulated_thresholds_resst_sui_sim9[9] + amount_of_SDs_perturbation * sd(thresholds_resst_sui_sim)
print(manipulated_thresholds_resst_sui_sim9) # .40

# Manipulate item 10's threshold
manipulated_thresholds_resst_sui_sim10 <- thresholds_resst_sui_sim
manipulated_thresholds_resst_sui_sim10[10] <- manipulated_thresholds_resst_sui_sim10[10] + amount_of_SDs_perturbation * sd(thresholds_resst_sui_sim)
print(manipulated_thresholds_resst_sui_sim10) # 1.18

# Manipulate item 11's threshold
manipulated_thresholds_resst_sui_sim11 <- thresholds_resst_sui_sim
manipulated_thresholds_resst_sui_sim11[11] <- manipulated_thresholds_resst_sui_sim11[11] + amount_of_SDs_perturbation * sd(thresholds_resst_sui_sim)
print(manipulated_thresholds_resst_sui_sim11) # -2.5

# Manipulate item 12's threshold
manipulated_thresholds_resst_sui_sim12 <- thresholds_resst_sui_sim
manipulated_thresholds_resst_sui_sim12[12] <- manipulated_thresholds_resst_sui_sim12[12] + amount_of_SDs_perturbation * sd(thresholds_resst_sui_sim)
print(manipulated_thresholds_resst_sui_sim12) # -.009

# Manipulate item 13's threshold
manipulated_thresholds_resst_sui_sim13 <- thresholds_resst_sui_sim
manipulated_thresholds_resst_sui_sim13[13] <- manipulated_thresholds_resst_sui_sim13[13] + amount_of_SDs_perturbation * sd(thresholds_resst_sui_sim)
print(manipulated_thresholds_resst_sui_sim13) # -.74

# Manipulate item 14's threshold
manipulated_thresholds_resst_sui_sim14 <- thresholds_resst_sui_sim
manipulated_thresholds_resst_sui_sim14[14] <- manipulated_thresholds_resst_sui_sim14[14] + amount_of_SDs_perturbation * sd(thresholds_resst_sui_sim)
print(manipulated_thresholds_resst_sui_sim14) # -1.27

# Manipulate item 15's threshold
manipulated_thresholds_resst_sui_sim15 <- thresholds_resst_sui_sim
manipulated_thresholds_resst_sui_sim15[15] <- manipulated_thresholds_resst_sui_sim15[15] + amount_of_SDs_perturbation * sd(thresholds_resst_sui_sim)
print(manipulated_thresholds_resst_sui_sim15) # -.33

# Manipulate item 16's threshold
manipulated_thresholds_resst_sui_sim16 <- thresholds_resst_sui_sim
manipulated_thresholds_resst_sui_sim16[16] <- manipulated_thresholds_resst_sui_sim16[16] + amount_of_SDs_perturbation * sd(thresholds_resst_sui_sim)
print(manipulated_thresholds_resst_sui_sim16) # -1.63

# Manipulate item 17's threshold
manipulated_thresholds_resst_sui_sim17 <- thresholds_resst_sui_sim
manipulated_thresholds_resst_sui_sim17[17] <- manipulated_thresholds_resst_sui_sim17[17] + amount_of_SDs_perturbation * sd(thresholds_resst_sui_sim)
print(manipulated_thresholds_resst_sui_sim17) # -.30

# Manipulate item 18's threshold
manipulated_thresholds_resst_sui_sim18 <- thresholds_resst_sui_sim
manipulated_thresholds_resst_sui_sim18[18] <- manipulated_thresholds_resst_sui_sim18[18] + amount_of_SDs_perturbation * sd(thresholds_resst_sui_sim)
print(manipulated_thresholds_resst_sui_sim18) # .70

# Manipulate item 19's threshold
manipulated_thresholds_resst_sui_sim19 <- thresholds_resst_sui_sim
manipulated_thresholds_resst_sui_sim19[19] <- manipulated_thresholds_resst_sui_sim19[19] + amount_of_SDs_perturbation * sd(thresholds_resst_sui_sim)
print(manipulated_thresholds_resst_sui_sim19) # .81

# Manipulate item 20's threshold
manipulated_thresholds_resst_sui_sim20 <- thresholds_resst_sui_sim
manipulated_thresholds_resst_sui_sim20[20] <- manipulated_thresholds_resst_sui_sim20[20] + amount_of_SDs_perturbation * sd(thresholds_resst_sui_sim)

print(manipulated_thresholds_resst_sui_sim20) # 1.16

# Manipulate item 21's threshold
manipulated_thresholds_resst_sui_sim21 <- thresholds_resst_sui_sim
manipulated_thresholds_resst_sui_sim21[21] <- manipulated_thresholds_resst_sui_sim21[21] + amount_of_SDs_perturbation * sd(thresholds_resst_sui_sim)

print(manipulated_thresholds_resst_sui_sim21) # .89

# equilbrium with item 1 manipulated #
set.seed(123456)
Glauber_1(connectivity_resst_sui_sim, manipulated_thresholds_resst_sui_sim1, Ntime = 20000, beta = 1.5)

Equilibrium_sui_1_manip <- output.binary_eq 
Equilibrium_sui_1_manip
stateEQ_sui_1_manip <- mean(apply(Equilibrium_sui_1_manip,1,sum)) 
stateEQ_sui_1_manip # 7.9635
stateEQ_sui_1_manip_sd <- sd(apply(Equilibrium_sui_1_manip,1,sum)) 
stateEQ_sui_1_manip_sd #  6.359406

# equilbrium with item 2 manipulated #
set.seed(123456)
Glauber_1(connectivity_resst_sui_sim, manipulated_thresholds_resst_sui_sim2, Ntime = 20000, beta = 1.5)

Equilibrium_sui_2_manip <- output.binary_eq 
Equilibrium_sui_2_manip
stateEQ_sui_2_manip <- mean(apply(Equilibrium_sui_2_manip,1,sum)) 
stateEQ_sui_2_manip # 7.6176
stateEQ_sui_2_manip_sd <- sd(apply(Equilibrium_sui_2_manip,1,sum)) 
stateEQ_sui_2_manip_sd # 4.866801

# equilbrium with item 3 manipulated #
set.seed(123456)
Glauber_1(connectivity_resst_sui_sim, manipulated_thresholds_resst_sui_sim3, Ntime = 20000, beta = 1.5)

Equilibrium_sui_3_manip <- output.binary_eq 
Equilibrium_sui_3_manip
stateEQ_sui_3_manip <- mean(apply(Equilibrium_sui_3_manip,1,sum)) 
stateEQ_sui_3_manip # 10.1696
stateEQ_sui_3_manip_sd <- sd(apply(Equilibrium_sui_3_manip,1,sum)) 
stateEQ_sui_3_manip_sd # 6.134453

# equilbrium with item 4 manipulated #
set.seed(123456)
Glauber_1(connectivity_resst_sui_sim, manipulated_thresholds_resst_sui_sim4, Ntime = 20000, beta = 1.5)

Equilibrium_sui_4_manip <- output.binary_eq 
Equilibrium_sui_4_manip
stateEQ_sui_4_manip <- mean(apply(Equilibrium_sui_4_manip,1,sum)) 
stateEQ_sui_4_manip # 10.1696
stateEQ_sui_4_manip_sd <- sd(apply(Equilibrium_sui_4_manip,1,sum)) 
stateEQ_sui_4_manip_sd # 6.134453

# equilbrium with item 5 manipulated #
set.seed(123456)
Glauber_1(connectivity_resst_sui_sim, manipulated_thresholds_resst_sui_sim5, Ntime = 20000, beta = 1.5)

Equilibrium_sui_5_manip <- output.binary_eq 
Equilibrium_sui_5_manip
stateEQ_sui_5_manip <- mean(apply(Equilibrium_sui_5_manip,1,sum)) 
stateEQ_sui_5_manip # 8.83975
stateEQ_sui_5_manip_sd <- sd(apply(Equilibrium_sui_5_manip,1,sum)) 
stateEQ_sui_5_manip_sd # 6.337845

# equilbrium with item 6 manipulated #
set.seed(123456)
Glauber_1(connectivity_resst_sui_sim, manipulated_thresholds_resst_sui_sim6, Ntime = 20000, beta = 1.5)

Equilibrium_sui_6_manip <- output.binary_eq 
Equilibrium_sui_6_manip
stateEQ_sui_6_manip <- mean(apply(Equilibrium_sui_6_manip,1,sum)) 
stateEQ_sui_6_manip # 9.3531
stateEQ_sui_6_manip_sd <- sd(apply(Equilibrium_sui_6_manip,1,sum)) 
stateEQ_sui_6_manip_sd # 6.317437

# equilbrium with item 7 manipulated #
set.seed(123456)
Glauber_1(connectivity_resst_sui_sim, manipulated_thresholds_resst_sui_sim7, Ntime = 20000, beta = 1.5)

Equilibrium_sui_7_manip <- output.binary_eq 
Equilibrium_sui_7_manip
stateEQ_sui_7_manip <- mean(apply(Equilibrium_sui_7_manip,1,sum)) 
stateEQ_sui_7_manip # 10.8352
stateEQ_sui_7_manip_sd <- sd(apply(Equilibrium_sui_7_manip,1,sum)) 
stateEQ_sui_7_manip_sd # 6.554517

# equilbrium with item 8 manipulated #
set.seed(123456)
Glauber_1(connectivity_resst_sui_sim, manipulated_thresholds_resst_sui_sim8, Ntime = 20000, beta = 1.5)

Equilibrium_sui_8_manip <- output.binary_eq 
Equilibrium_sui_8_manip
stateEQ_sui_8_manip <- mean(apply(Equilibrium_sui_8_manip,1,sum)) 
stateEQ_sui_8_manip # 11.72295
stateEQ_sui_8_manip_sd <- sd(apply(Equilibrium_sui_8_manip,1,sum)) 
stateEQ_sui_8_manip_sd # 6.169975

# equilbrium with item 9 manipulated #
set.seed(123456)
Glauber_1(connectivity_resst_sui_sim, manipulated_thresholds_resst_sui_sim9, Ntime = 20000, beta = 1.5)

Equilibrium_sui_9_manip <- output.binary_eq 
Equilibrium_sui_9_manip
stateEQ_sui_9_manip <- mean(apply(Equilibrium_sui_9_manip,1,sum)) 
stateEQ_sui_9_manip # 8.79185
stateEQ_sui_9_manip_sd <- sd(apply(Equilibrium_sui_9_manip,1,sum)) 
stateEQ_sui_9_manip_sd # 5.339733

# equilbrium with item 10 manipulated #
set.seed(123456)
Glauber_1(connectivity_resst_sui_sim, manipulated_thresholds_resst_sui_sim10, Ntime = 20000, beta = 1.5)

Equilibrium_sui_10_manip <- output.binary_eq 
Equilibrium_sui_10_manip
stateEQ_sui_10_manip <- mean(apply(Equilibrium_sui_10_manip,1,sum)) 
stateEQ_sui_10_manip # 7.86425
stateEQ_sui_10_manip_sd <- sd(apply(Equilibrium_sui_10_manip,1,sum)) 
stateEQ_sui_10_manip_sd # 5.320389

# equilbrium with item 11 manipulated #
set.seed(123456)
Glauber_1(connectivity_resst_sui_sim, manipulated_thresholds_resst_sui_sim11, Ntime = 20000, beta = 1.5) 

Equilibrium_sui_11_manip <- output.binary_eq 
Equilibrium_sui_11_manip
stateEQ_sui_11_manip <- mean(apply(Equilibrium_sui_11_manip,1,sum)) 
stateEQ_sui_11_manip # 10.71545
stateEQ_sui_11_manip_sd <- sd(apply(Equilibrium_sui_11_manip,1,sum)) 
stateEQ_sui_11_manip_sd # 6.547062

# equilbrium with item 12 manipulated #
set.seed(123456)
Glauber_1(connectivity_resst_sui_sim, manipulated_thresholds_resst_sui_sim12, Ntime = 20000, beta = 1.5) 

Equilibrium_sui_12_manip <- output.binary_eq 
Equilibrium_sui_12_manip
stateEQ_sui_12_manip <- mean(apply(Equilibrium_sui_12_manip,1,sum)) 
stateEQ_sui_12_manip # 10.4123
stateEQ_sui_12_manip_sd <- sd(apply(Equilibrium_sui_12_manip,1,sum)) 
stateEQ_sui_12_manip_sd # 6.300991

# equilbrium with item 13 manipulated #
set.seed(123456)
Glauber_1(connectivity_resst_sui_sim, manipulated_thresholds_resst_sui_sim13, Ntime = 20000, beta = 1.5) 

Equilibrium_sui_13_manip <- output.binary_eq 
Equilibrium_sui_13_manip
stateEQ_sui_13_manip <- mean(apply(Equilibrium_sui_13_manip,1,sum)) 
stateEQ_sui_13_manip # 9.84785
stateEQ_sui_13_manip_sd <- sd(apply(Equilibrium_sui_13_manip,1,sum)) 
stateEQ_sui_13_manip_sd # 6.030018

# equilbrium with item 14 manipulated #
set.seed(123456)
Glauber_1(connectivity_resst_sui_sim, manipulated_thresholds_resst_sui_sim14, Ntime = 20000, beta = 1.5)

Equilibrium_sui_14_manip <- output.binary_eq 
Equilibrium_sui_14_manip
stateEQ_sui_14_manip <- mean(apply(Equilibrium_sui_14_manip,1,sum)) 
stateEQ_sui_14_manip # 9.63855
stateEQ_sui_14_manip_sd <- sd(apply(Equilibrium_sui_14_manip,1,sum)) 
stateEQ_sui_14_manip_sd # 6.17593

# equilbrium with item 15 manipulated #
set.seed(123456)
Glauber_1(connectivity_resst_sui_sim, manipulated_thresholds_resst_sui_sim15, Ntime = 20000, beta = 1.5) 

Equilibrium_sui_15_manip <- output.binary_eq 
Equilibrium_sui_15_manip
stateEQ_sui_15_manip <- mean(apply(Equilibrium_sui_15_manip,1,sum)) 
stateEQ_sui_15_manip # 10.15005
stateEQ_sui_15_manip_sd <- sd(apply(Equilibrium_sui_15_manip,1,sum)) 
stateEQ_sui_15_manip_sd # 5.520947

# equilbrium with item 16 manipulated #
set.seed(123456)
Glauber_1(connectivity_resst_sui_sim, manipulated_thresholds_resst_sui_sim16, Ntime = 20000, beta = 1.5) 

Equilibrium_sui_16_manip <- output.binary_eq 
Equilibrium_sui_16_manip
stateEQ_sui_16_manip <- mean(apply(Equilibrium_sui_16_manip,1,sum)) 
stateEQ_sui_16_manip # 9.2583
stateEQ_sui_16_manip_sd <- sd(apply(Equilibrium_sui_16_manip,1,sum)) 
stateEQ_sui_16_manip_sd # 5.179124

# equilbrium with item 17 manipulated #
set.seed(123456)
Glauber_1(connectivity_resst_sui_sim, manipulated_thresholds_resst_sui_sim17, Ntime = 20000, beta = 1.5) 

Equilibrium_sui_17_manip <- output.binary_eq 
Equilibrium_sui_17_manip
stateEQ_sui_17_manip <- mean(apply(Equilibrium_sui_17_manip,1,sum)) 
stateEQ_sui_17_manip # 10.8947
stateEQ_sui_17_manip_sd <- sd(apply(Equilibrium_sui_17_manip,1,sum)) 
stateEQ_sui_17_manip_sd # 5.571137

# equilbrium with item 18 manipulated #
set.seed(123456)
Glauber_1(connectivity_resst_sui_sim, manipulated_thresholds_resst_sui_sim18, Ntime = 20000, beta = 1.5) 

Equilibrium_sui_18_manip <- output.binary_eq 
Equilibrium_sui_18_manip
stateEQ_sui_18_manip <- mean(apply(Equilibrium_sui_18_manip,1,sum)) 
stateEQ_sui_18_manip # 7.94855
stateEQ_sui_18_manip_sd <- sd(apply(Equilibrium_sui_18_manip,1,sum)) 
stateEQ_sui_18_manip_sd # 5.375309

# equilbrium with item 19 manipulated #
set.seed(123456)
Glauber_1(connectivity_resst_sui_sim, manipulated_thresholds_resst_sui_sim19, Ntime = 20000, beta = 1.5) 

Equilibrium_sui_19_manip <- output.binary_eq 
Equilibrium_sui_19_manip
stateEQ_sui_19_manip <- mean(apply(Equilibrium_sui_19_manip,1,sum)) 
stateEQ_sui_19_manip # 7.88185
stateEQ_sui_19_manip_sd <- sd(apply(Equilibrium_sui_19_manip,1,sum)) 
stateEQ_sui_19_manip_sd # 5.502691

# equilbrium with item 20 manipulated #
set.seed(123456)
Glauber_1(connectivity_resst_sui_sim, manipulated_thresholds_resst_sui_sim20, Ntime = 20000, beta = 1.5)

Equilibrium_sui_20_manip <- output.binary_eq 
Equilibrium_sui_20_manip
stateEQ_sui_20_manip <- mean(apply(Equilibrium_sui_20_manip,1,sum)) 
stateEQ_sui_20_manip # 7.4975
stateEQ_sui_20_manip_sd <- sd(apply(Equilibrium_sui_20_manip,1,sum)) 
stateEQ_sui_20_manip_sd # 5.254358

# equilbrium with item 21 manipulated #
set.seed(123456)
Glauber_1(connectivity_resst_sui_sim, manipulated_thresholds_resst_sui_sim21, Ntime = 20000, beta = 1.5)

Equilibrium_sui_21_manip <- output.binary_eq 
Equilibrium_sui_21_manip
stateEQ_sui_21_manip <- mean(apply(Equilibrium_sui_21_manip,1,sum)) 
stateEQ_sui_21_manip # 7.37835
stateEQ_sui_21_manip_sd <- sd(apply(Equilibrium_sui_21_manip,1,sum)) 
stateEQ_sui_21_manip_sd # 5.036861

## dataframes with totals for each glauber simulation ##

DF_simulations_sui_1m <- data.frame(Timepoints = 1:Ntime,
                         Equilibrium = apply(Equilibrium_sui_1_manip,1,sum)) 

DF_simulations_sui_2m <- data.frame(Timepoints = 1:Ntime,
                         Equilibrium = apply(Equilibrium_sui_2_manip,1,sum)) 

DF_simulations_sui_3m <- data.frame(Timepoints = 1:Ntime,
                         Equilibrium = apply(Equilibrium_sui_3_manip,1,sum)) 

DF_simulations_sui_4m <- data.frame(Timepoints = 1:Ntime,
                         Equilibrium = apply(Equilibrium_sui_4_manip,1,sum)) 

DF_simulations_sui_5m <- data.frame(Timepoints = 1:Ntime,
                         Equilibrium = apply(Equilibrium_sui_5_manip,1,sum)) 

DF_simulations_sui_6m <- data.frame(Timepoints = 1:Ntime,
                         Equilibrium = apply(Equilibrium_sui_6_manip,1,sum)) 

DF_simulations_sui_7m <- data.frame(Timepoints = 1:Ntime,
                         Equilibrium = apply(Equilibrium_sui_7_manip,1,sum)) 

DF_simulations_sui_8m <- data.frame(Timepoints = 1:Ntime,
                         Equilibrium = apply(Equilibrium_sui_8_manip,1,sum)) 

DF_simulations_sui_9m <- data.frame(Timepoints = 1:Ntime,
                         Equilibrium = apply(Equilibrium_sui_9_manip,1,sum)) 

DF_simulations_sui_10m <- data.frame(Timepoints = 1:Ntime,
                         Equilibrium = apply(Equilibrium_sui_10_manip,1,sum)) 

DF_simulations_sui_11m <- data.frame(Timepoints = 1:Ntime,
                         Equilibrium = apply(Equilibrium_sui_11_manip,1,sum)) 

DF_simulations_sui_12m <- data.frame(Timepoints = 1:Ntime,
                         Equilibrium = apply(Equilibrium_sui_12_manip,1,sum)) 

DF_simulations_sui_13m <- data.frame(Timepoints = 1:Ntime,
                         Equilibrium = apply(Equilibrium_sui_13_manip,1,sum)) 

DF_simulations_sui_14m <- data.frame(Timepoints = 1:Ntime,
                         Equilibrium = apply(Equilibrium_sui_14_manip,1,sum)) 

DF_simulations_sui_15m <- data.frame(Timepoints = 1:Ntime,
                         Equilibrium = apply(Equilibrium_sui_15_manip,1,sum)) 

DF_simulations_sui_16m <- data.frame(Timepoints = 1:Ntime,
                         Equilibrium = apply(Equilibrium_sui_16_manip,1,sum)) 

DF_simulations_sui_17m <- data.frame(Timepoints = 1:Ntime,
                         Equilibrium = apply(Equilibrium_sui_17_manip,1,sum)) 

DF_simulations_sui_18m <- data.frame(Timepoints = 1:Ntime,
                         Equilibrium = apply(Equilibrium_sui_18_manip,1,sum)) 

DF_simulations_sui_19m <- data.frame(Timepoints = 1:Ntime,
                         Equilibrium = apply(Equilibrium_sui_19_manip,1,sum)) 

DF_simulations_sui_20m <- data.frame(Timepoints = 1:Ntime,
                         Equilibrium = apply(Equilibrium_sui_20_manip,1,sum)) 

DF_simulations_sui_21m <- data.frame(Timepoints = 1:Ntime,
                         Equilibrium = apply(Equilibrium_sui_21_manip,1,sum))

# IQR, mean, range
summ_1m_sui <- summary(DF_simulations_sui_1m$Equilibrium)
summ_2m_sui <- summary(DF_simulations_sui_2m$Equilibrium)
summ_3m_sui <- summary(DF_simulations_sui_3m$Equilibrium)
summ_4m_sui <- summary(DF_simulations_sui_4m$Equilibrium)
summ_5m_sui <- summary(DF_simulations_sui_5m$Equilibrium)
summ_6m_sui <- summary(DF_simulations_sui_6m$Equilibrium)
summ_7m_sui <- summary(DF_simulations_sui_7m$Equilibrium)
summ_8m_sui <- summary(DF_simulations_sui_8m$Equilibrium)
summ_9m_sui <- summary(DF_simulations_sui_9m$Equilibrium)
summ_10m_sui <- summary(DF_simulations_sui_10m$Equilibrium)
summ_11m_sui <- summary(DF_simulations_sui_11m$Equilibrium)
summ_12m_sui <- summary(DF_simulations_sui_12m$Equilibrium)
summ_13m_sui <- summary(DF_simulations_sui_13m$Equilibrium)
summ_14m_sui <- summary(DF_simulations_sui_14m$Equilibrium)
summ_15m_sui <- summary(DF_simulations_sui_15m$Equilibrium)
summ_16m_sui <- summary(DF_simulations_sui_16m$Equilibrium)
summ_17m_sui <- summary(DF_simulations_sui_17m$Equilibrium)
summ_18m_sui <- summary(DF_simulations_sui_18m$Equilibrium)
summ_19m_sui <- summary(DF_simulations_sui_19m$Equilibrium)
summ_20m_sui <- summary(DF_simulations_sui_20m$Equilibrium)
summ_21m_sui <- summary(DF_simulations_sui_21m$Equilibrium)

# Save csv files 
# raw simulated data
write.csv(Equilibrium_sui_1_manip, "Sui_data_output/DF_sui_equilibrium_1_manipulated.csv")
write.csv(Equilibrium_sui_2_manip, "Sui_data_output/DF_sui_equilibrium_2_manipulated.csv")
write.csv(Equilibrium_sui_3_manip, "Sui_data_output/DF_sui_equilibrium_3_manipulated.csv")
write.csv(Equilibrium_sui_4_manip, "Sui_data_output/DF_sui_equilibrium_4_manipulated.csv")
write.csv(Equilibrium_sui_5_manip, "Sui_data_output/DF_sui_equilibrium_5_manipulated.csv")
write.csv(Equilibrium_sui_6_manip, "Sui_data_output/DF_sui_equilibrium_6_manipulated.csv")
write.csv(Equilibrium_sui_7_manip, "Sui_data_output/DF_sui_equilibrium_7_manipulated.csv")
write.csv(Equilibrium_sui_8_manip, "Sui_data_output/DF_sui_equilibrium_8_manipulated.csv")
write.csv(Equilibrium_sui_9_manip, "Sui_data_output/DF_sui_equilibrium_9_manipulated.csv")
write.csv(Equilibrium_sui_10_manip, "Sui_data_output/DF_sui_equilibrium_10_manipulated.csv")
write.csv(Equilibrium_sui_11_manip, "Sui_data_output/DF_sui_equilibrium_11_manipulated.csv")
write.csv(Equilibrium_sui_12_manip, "Sui_data_output/DF_sui_equilibrium_12_manipulated.csv")
write.csv(Equilibrium_sui_13_manip, "Sui_data_output/DF_sui_equilibrium_13_manipulated.csv")
write.csv(Equilibrium_sui_14_manip, "Sui_data_output/DF_sui_equilibrium_14_manipulated.csv")
write.csv(Equilibrium_sui_15_manip, "Sui_data_output/DF_sui_equilibrium_15_manipulated.csv")
write.csv(Equilibrium_sui_16_manip, "Sui_data_output/DF_sui_equilibrium_16_manipulated.csv")
write.csv(Equilibrium_sui_17_manip, "Sui_data_output/DF_sui_equilibrium_17_manipulated.csv")
write.csv(Equilibrium_sui_18_manip, "Sui_data_output/DF_sui_equilibrium_18_manipulated.csv")
write.csv(Equilibrium_sui_19_manip, "Sui_data_output/DF_sui_equilibrium_19_manipulated.csv")
write.csv(Equilibrium_sui_20_manip, "Sui_data_output/DF_sui_equilibrium_20_manipulated.csv")
write.csv(Equilibrium_sui_21_manip, "Sui_data_output/DF_sui_equilibrium_21_manipulated.csv")
# totals
write.csv(DF_simulations_sui_1m, "Sui_data_output/DF_sui_simulations_1_manipulated.csv")
write.csv(DF_simulations_sui_2m, "Sui_data_output/DF_sui_simulations_2_manipulated.csv")
write.csv(DF_simulations_sui_3m, "Sui_data_output/DF_sui_simulations_3_manipulated.csv")
write.csv(DF_simulations_sui_4m, "Sui_data_output/DF_sui_simulations_4_manipulated.csv")
write.csv(DF_simulations_sui_5m, "Sui_data_output/DF_sui_simulations_5_manipulated.csv")
write.csv(DF_simulations_sui_6m, "Sui_data_output/DF_sui_simulations_6_manipulated.csv")
write.csv(DF_simulations_sui_7m, "Sui_data_output/DF_sui_simulations_7_manipulated.csv")
write.csv(DF_simulations_sui_8m, "Sui_data_output/DF_sui_simulations_8_manipulated.csv")
write.csv(DF_simulations_sui_9m, "Sui_data_output/DF_sui_simulations_9_manipulated.csv")
write.csv(DF_simulations_sui_10m, "Sui_data_output/DF_sui_simulations_10_manipulated.csv")
write.csv(DF_simulations_sui_11m, "Sui_data_output/DF_sui_simulations_11_manipulated.csv")
write.csv(DF_simulations_sui_12m, "Sui_data_output/DF_sui_simulations_12_manipulated.csv")
write.csv(DF_simulations_sui_13m, "Sui_data_output/DF_sui_simulations_13_manipulated.csv")
write.csv(DF_simulations_sui_14m, "Sui_data_output/DF_sui_simulations_14_manipulated.csv")
write.csv(DF_simulations_sui_15m, "Sui_data_output/DF_sui_simulations_15_manipulated.csv")
write.csv(DF_simulations_sui_16m, "Sui_data_output/DF_sui_simulations_16_manipulated.csv")
write.csv(DF_simulations_sui_17m, "Sui_data_output/DF_sui_simulations_17_manipulated.csv")
write.csv(DF_simulations_sui_18m, "Sui_data_output/DF_sui_simulations_18_manipulated.csv")
write.csv(DF_simulations_sui_19m, "Sui_data_output/DF_sui_simulations_19_manipulated.csv")
write.csv(DF_simulations_sui_20m, "Sui_data_output/DF_sui_simulations_20_manipulated.csv")
write.csv(DF_simulations_sui_21m, "Sui_data_output/DF_sui_simulations_21_manipulated.csv")

glimpse(DF_simulations_sui_21m)
```

```{r  S simulations INDIVIDUAL item table descriptives}

summaries <- list(summ_1m_sui, summ_2m_sui, summ_3m_sui, summ_4m_sui, summ_5m_sui, summ_6m_sui,
                  summ_7m_sui, summ_8m_sui, summ_9m_sui, summ_10m_sui, summ_11m_sui, summ_12m_sui,
                  summ_13m_sui, summ_14m_sui, summ_15m_sui, summ_16m_sui, summ_17m_sui, summ_18m_sui,
                  summ_19m_sui, summ_20m_sui, summ_21m_sui)

means <- c(stateEQ_sui_1_manip, stateEQ_sui_2_manip, stateEQ_sui_3_manip, stateEQ_sui_4_manip,
           stateEQ_sui_5_manip, stateEQ_sui_6_manip, stateEQ_sui_7_manip, stateEQ_sui_8_manip,
           stateEQ_sui_9_manip, stateEQ_sui_10_manip, stateEQ_sui_11_manip, stateEQ_sui_12_manip,
           stateEQ_sui_13_manip, stateEQ_sui_14_manip, stateEQ_sui_15_manip, stateEQ_sui_16_manip,
           stateEQ_sui_17_manip, stateEQ_sui_18_manip, stateEQ_sui_19_manip, stateEQ_sui_20_manip,
           stateEQ_sui_21_manip)

sds <- c(stateEQ_sui_1_manip_sd, stateEQ_sui_2_manip_sd, stateEQ_sui_3_manip_sd, stateEQ_sui_4_manip_sd,
         stateEQ_sui_5_manip_sd, stateEQ_sui_6_manip_sd, stateEQ_sui_7_manip_sd, stateEQ_sui_8_manip_sd,
         stateEQ_sui_9_manip_sd, stateEQ_sui_10_manip_sd, stateEQ_sui_11_manip_sd, stateEQ_sui_12_manip_sd,
         stateEQ_sui_13_manip_sd, stateEQ_sui_14_manip_sd, stateEQ_sui_15_manip_sd, stateEQ_sui_16_manip_sd,
         stateEQ_sui_17_manip_sd, stateEQ_sui_18_manip_sd, stateEQ_sui_19_manip_sd, stateEQ_sui_20_manip_sd,
         stateEQ_sui_21_manip_sd)

medians <- sapply(summaries, function(x) x[3])
ranges <- sapply(summaries, function(x) x[6] - x[1])
iqr <- sapply(summaries, function(x) x[5] - x[2])
q1 <- sapply(summaries, function(x) x[2])
q3 <- sapply(summaries, function(x) x[5])

data_means_sds <- data.frame(Item = 1:21, Mean = means, SD = sds)

data_summary <- data.frame(Item = 1:21, Median = medians, Range = ranges, IQR = iqr, Q1 = q1, Q3 = q3)

table_desc_sui <- merge(data_means_sds, data_summary, by = "Item")

print(table_desc_sui)

original_plot <- ggplot(DF_simulations_sui, aes(x = Equilibrium)) +
  geom_density(fill = "grey", alpha = 0.5) +
  labs(title = "Original",
       x = NULL,  
       y = NULL) +  
  theme(
    panel.background = element_rect(fill = "white"),
    panel.grid.major = element_line(color = "grey", linetype = "dashed"),
    panel.grid.minor = element_line(color = "grey", linetype = "dashed"),
    text = element_text(size = 7, family = "serif"),
    plot.title = element_text(family = "serif", size = 8, hjust = 0.5)
  )

plot_list <- list()
colors <- rainbow(21)
for (i in 1:21) {
  df_name_manipulated <- paste0("DF_simulations_sui_", i, "m")
  
  DF_manipulated <- get(df_name_manipulated)
  
  current_plot <- ggplot(DF_manipulated, aes(x = Equilibrium)) +
    geom_density(fill = colors[i], alpha = 0.5) +
    geom_density(data = DF_simulations_sui, fill = "grey", alpha = 0.5) +
    labs(title = paste("Item", i),
         x = NULL,  
         y = NULL) +  
    theme(
      panel.background = element_rect(fill = "white"),
      panel.grid.major = element_line(color = "grey", linetype = "dashed"),
      panel.grid.minor = element_line(color = "grey", linetype = "dashed"),
      text = element_text(size = 7, family = "serif"),
      plot.title = element_text(family = "serif", size = 8, hjust = 0.5)
    )
  
  plot_list[[i]] <- current_plot
}

grid.arrange(original_plot, grobs = plot_list, ncol = 7)

pdf("Sui_data_output/Figures/Sui_simulation_equilibrium_density.pdf", width=8.75, height=5.45)
grid.arrange(grobs = plot_list, ncol = 7)
dev.off()
```

```{r S simulations INDIVIDUAL manipulations total}
get_variable_totals <- function(df) {
  data.frame(variable = paste0("R", 1:ncol(df)), count = colSums(df))
}

total_1m_s <- get_variable_totals(Equilibrium_sui_1_manip)
total_2m_s <- get_variable_totals(Equilibrium_sui_2_manip)
total_3m_s <- get_variable_totals(Equilibrium_sui_3_manip)
total_4m_s <- get_variable_totals(Equilibrium_sui_4_manip)
total_5m_s <- get_variable_totals(Equilibrium_sui_5_manip)
total_6m_s <- get_variable_totals(Equilibrium_sui_6_manip)
total_7m_s <- get_variable_totals(Equilibrium_sui_7_manip)
total_8m_s <- get_variable_totals(Equilibrium_sui_8_manip)
total_9m_s <- get_variable_totals(Equilibrium_sui_9_manip)
total_10m_s <- get_variable_totals(Equilibrium_sui_10_manip)
total_11m_s <- get_variable_totals(Equilibrium_sui_11_manip)
total_12m_s <- get_variable_totals(Equilibrium_sui_12_manip)
total_13m_s <- get_variable_totals(Equilibrium_sui_13_manip)
total_14m_s <- get_variable_totals(Equilibrium_sui_14_manip)
total_15m_s <- get_variable_totals(Equilibrium_sui_15_manip)
total_16m_s <- get_variable_totals(Equilibrium_sui_16_manip)
total_17m_s <- get_variable_totals(Equilibrium_sui_17_manip)
total_18m_s <- get_variable_totals(Equilibrium_sui_18_manip)
total_19m_s <- get_variable_totals(Equilibrium_sui_19_manip)
total_20m_s <- get_variable_totals(Equilibrium_sui_20_manip)
total_21m_s <- get_variable_totals(Equilibrium_sui_21_manip)


total_manipulated_s <- data.frame(
  total_1m_s,
  total_2m_s,
  total_3m_s,
  total_4m_s,
  total_5m_s,
  total_6m_s,
  total_7m_s,
  total_8m_s,
  total_9m_s,
  total_10m_s,
  total_11m_s,
  total_12m_s,
  total_13m_s,
  total_14m_s,
  total_15m_s,
  total_16m_s,
  total_17m_s,
  total_18m_s,
  total_19m_s,
  total_20m_s,
  total_21m_s
)

print(total_manipulated_s)

write.csv(total_manipulated_s, 'Sui_data_output/DF_sui_equilibrium_manipulated_totals.csv') # totals
```

```{r S simulations individual pre and post manipulation}
# DF_simulations_sui is  pre-test (no manipulations)
# DF_simulations_sui_[ITEM]m is post-test (item manipulation)
 
## for each paired t test, we need to EXCLUDE the item that is being manipulated. e.g., when comparing total average system activation at equilibrium vs after 1 was manipulated, exclude item 1; when comparing total system activation at equilibrium vs after 19 was manipulated, exclude item 19. Otherwise, this manipulation will conflate the effect ##

### make datasets at equilibrium EXCLUDING manipulated item: 21 new columns  

Ntime <- nrow(Equilibrium_sui_1_manip) 
df_list <- list()

for (i in 1:21) {
  manipulated_matrix <- get(paste0("Equilibrium_sui_", i, "_manip"))
  #### exclude the corresponding item (column) based on the scenario index
  manipulated_matrix <- manipulated_matrix[, -i, drop = FALSE]
  df <- data.frame(Timepoints = 1:Ntime,
                   Equilibrium = apply(manipulated_matrix, 1, sum))
  df_name <- paste0("DF_simulations_sui_", i, "m")
  df_list[[df_name]] <- df
}

list2env(df_list, envir = .GlobalEnv)

for (i in 1:21) {
  df_name <- paste0("DF_simulations_sui_", i, "m")
  print(head(get(df_name)))
}

combined_data <- do.call(cbind, df_list)
print(head(combined_data))

### now make dataset at equilibrium, with NO manipulated datasets, excluding item 1, item 2, etc. to match the paired data
# original: DF_simulations_sui <- data.frame(Timepoints = 1:Ntime, Equilibrium = apply(Equilibrium_sui,1,sum))

Ntime <- nrow(Equilibrium_sui)

df_list_minus <- list()

for (i in 1:ncol(Equilibrium_sui)) {
  excluded_matrix <- Equilibrium_sui[, -i, drop = FALSE]
  df_minus <- data.frame(Timepoints = 1:Ntime,
                         Equilibrium = apply(excluded_matrix, 1, sum))
  df_name_minus <- paste0("DF_sim_sui_minus", i)
  df_list_minus[[df_name_minus]] <- df_minus
}

for (i in 1:length(df_list_minus)) {
  df_name_minus <- paste0("DF_sim_sui_minus", i)
  print(head(df_list_minus[[df_name_minus]]))
}

combined_data_minus <- df_list_minus[[1]]

for (i in 2:length(df_list_minus)) {
  df_minus <- df_list_minus[[i]]
  col_name_minus <- paste("Equilibrium_minus", i, sep = "")
  col_name_minus <- make.names(col_name_minus, unique = TRUE)  # Ensure valid column names
  names(df_minus)[names(df_minus) == "Equilibrium"] <- col_name_minus
  combined_data_minus <- cbind(combined_data_minus, df_minus[col_name_minus])
}

print(head(combined_data_minus))

## combine manipulated item dataframes (that exclude the manipulated item) and the equilibrium sui dataframes that exclude the maniulated item 

combined_data_all <- cbind(combined_data, combined_data_minus)
print(head(combined_data_all))

## paired t tests between the equilibrium dataframe pre and post manipulated item, excluding the manipulated item from both

paired_t <- jmv::ttestPS(
    data = combined_data_all, # our combined dataframe with equilibrium columns minus individual manipulated items and manipulated dataframes minus manipulated item
    pairs = list(
        list(
            i1="DF_simulations_sui_1m.Equilibrium",
            i2="Equilibrium"),
        list(
            i1="DF_simulations_sui_2m.Equilibrium",
            i2="Equilibrium_minus2"),
        list(
            i1="DF_simulations_sui_3m.Equilibrium",
            i2="Equilibrium_minus3"),
        list(
            i1="DF_simulations_sui_4m.Equilibrium",
            i2="Equilibrium_minus4"),
        list(
            i1="DF_simulations_sui_5m.Equilibrium",
            i2="Equilibrium_minus5"),
        list(
            i1="DF_simulations_sui_6m.Equilibrium",
            i2="Equilibrium_minus6"),
        list(
            i1="DF_simulations_sui_7m.Equilibrium",
            i2="Equilibrium_minus7"),
        list(
            i1="DF_simulations_sui_8m.Equilibrium",
            i2="Equilibrium_minus8"),
        list(
            i1="DF_simulations_sui_9m.Equilibrium",
            i2="Equilibrium_minus9"),
        list(
            i1="DF_simulations_sui_10m.Equilibrium",
            i2="Equilibrium_minus10"),
        list(
            i1="DF_simulations_sui_11m.Equilibrium",
            i2="Equilibrium_minus11"),
        list(
            i1="DF_simulations_sui_12m.Equilibrium",
            i2="Equilibrium_minus12"),
        list(
            i1="DF_simulations_sui_13m.Equilibrium",
            i2="Equilibrium_minus13"),
        list(
            i1="DF_simulations_sui_14m.Equilibrium",
            i2="Equilibrium_minus14"),
        list(
            i1="DF_simulations_sui_15m.Equilibrium",
            i2="Equilibrium_minus15"),
        list(
            i1="DF_simulations_sui_16m.Equilibrium",
            i2="Equilibrium_minus16"),
        list(
            i1="DF_simulations_sui_17m.Equilibrium",
            i2="Equilibrium_minus17"),
        list(
            i1="DF_simulations_sui_18m.Equilibrium",
            i2="Equilibrium_minus18"),
        list(
            i1="DF_simulations_sui_19m.Equilibrium",
            i2="Equilibrium_minus19"),
        list(
            i1="DF_simulations_sui_20m.Equilibrium",
            i2="Equilibrium_minus20"),
        list(
            i1="DF_simulations_sui_21m.Equilibrium",
            i2="Equilibrium_minus21")),
    effectSize = TRUE,
    ciES = TRUE,
    desc = TRUE)

paired_t$ttest
paired_t$desc

as.data.frame(paired_t$ttest)
as.data.frame(paired_t$desc)
```

```{r S individual manipulation simulation plots}
## plots at equilibrium ## 

plot_list <- list()

for (i in 1:21) {
  df_name_manipulated <- paste0("DF_simulations_sui_", i, "m")
  DF_manipulated <- transform(get(df_name_manipulated), Type = "Manipulated")
  
  current_plot <- ggplot(DF_manipulated, aes(x = Timepoints, y = Equilibrium)) +
    geom_line(color = "black") +  
    theme_classic() +
    labs(title = paste("Item", i), 
         x = NULL,  
         y = NULL) +  
    theme(
      plot.title = element_text(family = "serif", size = 8, hjust = 0.5),
      axis.title = element_blank(),  
      axis.text = element_text(family = "serif", size = 6),
      legend.position = "none"  
    ) +
    scale_x_continuous(breaks = c(0, 10000, 20000))

  plot_list[[i]] <- current_plot
}

grid.arrange(grobs = plot_list, ncol = 7)
```

```{r S overlap original and manipulated (individual) equilibrium plots}

DF_simulations_sui_ori <- DF_simulations_sui[, c("Timepoints", "Equilibrium")] # original equilibrium for suicide group (remove perturbations colmn to match the manipulated equilibrium dataframe)

plot_list <- list()

for (i in 1:21) {
  df_name_ori <- "DF_simulations_sui_ori"
  df_name_manipulated <- paste0("DF_simulations_sui_", i, "m")
  
  DF_combined <- rbind(
    transform(get(df_name_ori), Type = "Original"),
    transform(get(df_name_manipulated), Type = "Manipulated")
  )
  
  current_plot <- ggplot(DF_combined, aes(x = Timepoints, y = Equilibrium, color = Type)) +
    geom_line() +
    scale_color_manual(values = c("#CC99FF", "#663399")) +  
    theme_classic() +
    labs(title = paste("Item", i), 
         x = NULL, 
         y = NULL) +  
    theme(
      plot.title = element_text(family = "serif", size = 10, hjust = 0.5),
      axis.title = element_blank(),  
      axis.text = element_text(family = "serif", size = 8),
      legend.position = "none"  
    ) +
    scale_x_continuous(breaks = c(0, 10000, 20000))
  
  plot_list[[i]] <- current_plot
}

#grid.arrange(grobs = plot_list, ncol = 7)

#pdf("Sui_data_output/Figures/Sui_simulation_equilibrium_plots.pdf", width=8.37, height=5.17)
#grid.arrange(grobs = plot_list, ncol = 7)
#dev.off()

pdf("Sui_data_output/Figures/Sui_simulation_equilibrium_ind_plots.pdf", width=8.37, height=5.17) # all time points
plot_list
dev.off()
```

```{r S individual manipulations system activity preferences}
# connectivity_resst_sui_sim = RESST_sui_binary_res$weiadj 
# thresholds_resst__sui_sim = manipulated_thresholds_resst_sui_sim[# that is manipulated]

set.seed(123456)
lm1 <- make_2d_Isingland(thresholds = manipulated_thresholds_resst_sui_sim1, 
                        weiadj = RESST_sui_binary_res$weiadj, 
                        beta = 1, 
                        transform = TRUE)

plot(lm1)
calculate_resilience(lm1)


set.seed(123456)
lm2 <- make_2d_Isingland(thresholds = manipulated_thresholds_resst_sui_sim2, 
                        weiadj = RESST_sui_binary_res$weiadj, 
                        beta = 1, 
                        transform = TRUE)

plot(lm2)
calculate_resilience(lm2)

set.seed(123456)
lm3 <- make_2d_Isingland(thresholds = manipulated_thresholds_resst_sui_sim3, 
                        weiadj = RESST_sui_binary_res$weiadj, 
                        beta = 1, 
                        transform = TRUE)

plot(lm3)
calculate_resilience(lm3)


set.seed(123456)
lm4 <- make_2d_Isingland(thresholds = manipulated_thresholds_resst_sui_sim4, 
                        weiadj = RESST_sui_binary_res$weiadj, 
                        beta = 1, 
                        transform = TRUE)

plot(lm4)
calculate_resilience(lm4)

set.seed(123456)
lm5 <- make_2d_Isingland(thresholds = manipulated_thresholds_resst_sui_sim5, 
                        weiadj = RESST_sui_binary_res$weiadj, 
                        beta = 1, 
                        transform = TRUE)

plot(lm5)
calculate_resilience(lm5)


set.seed(123456)
lm6 <- make_2d_Isingland(thresholds = manipulated_thresholds_resst_sui_sim6, 
                        weiadj = RESST_sui_binary_res$weiadj, 
                        beta = 1, 
                        transform = TRUE)

plot(lm6)
calculate_resilience(lm6)

set.seed(123456)
lm7 <- make_2d_Isingland(thresholds = manipulated_thresholds_resst_sui_sim7, 
                        weiadj = RESST_sui_binary_res$weiadj, 
                        beta = 1, 
                        transform = TRUE)

plot(lm7)
calculate_resilience(lm7)


set.seed(123456)
lm8 <- make_2d_Isingland(thresholds = manipulated_thresholds_resst_sui_sim8, 
                        weiadj = RESST_sui_binary_res$weiadj, 
                        beta = 1, 
                        transform = TRUE)

plot(lm8)
calculate_resilience(lm8)

set.seed(123456)
lm9 <- make_2d_Isingland(thresholds = manipulated_thresholds_resst_sui_sim9, 
                        weiadj = RESST_sui_binary_res$weiadj, 
                        beta = 1, 
                        transform = TRUE)

plot(lm9)
calculate_resilience(lm9)


set.seed(123456)
lm10 <- make_2d_Isingland(thresholds = manipulated_thresholds_resst_sui_sim10, 
                        weiadj = RESST_sui_binary_res$weiadj, 
                        beta = 1, 
                        transform = TRUE)

plot(lm10)
calculate_resilience(lm10)

set.seed(123456)
lm11 <- make_2d_Isingland(thresholds = manipulated_thresholds_resst_sui_sim11, 
                        weiadj = RESST_sui_binary_res$weiadj, 
                        beta = 1, 
                        transform = TRUE)

plot(lm11)
calculate_resilience(lm11)


set.seed(123456)
lm12 <- make_2d_Isingland(thresholds = manipulated_thresholds_resst_sui_sim12, 
                        weiadj = RESST_sui_binary_res$weiadj, 
                        beta = 1, 
                        transform = TRUE)

plot(lm12)
calculate_resilience(lm12)

set.seed(123456)
lm13 <- make_2d_Isingland(thresholds = manipulated_thresholds_resst_sui_sim13, 
                        weiadj = RESST_sui_binary_res$weiadj, 
                        beta = 1, 
                        transform = TRUE)

plot(lm13)
calculate_resilience(lm13)


set.seed(123456)
lm14 <- make_2d_Isingland(thresholds = manipulated_thresholds_resst_sui_sim14, 
                        weiadj = RESST_sui_binary_res$weiadj, 
                        beta = 1, 
                        transform = TRUE)

plot(lm14)
calculate_resilience(lm14)

set.seed(123456)
lm15 <- make_2d_Isingland(thresholds = manipulated_thresholds_resst_sui_sim15, 
                        weiadj = RESST_sui_binary_res$weiadj, 
                        beta = 1, 
                        transform = TRUE)

plot(lm15)
calculate_resilience(lm15)


set.seed(123456)
lm16 <- make_2d_Isingland(thresholds = manipulated_thresholds_resst_sui_sim16, 
                        weiadj = RESST_sui_binary_res$weiadj, 
                        beta = 1, 
                        transform = TRUE)

plot(lm16)
calculate_resilience(lm16)

set.seed(123456)
lm17 <- make_2d_Isingland(thresholds = manipulated_thresholds_resst_sui_sim17, 
                        weiadj = RESST_sui_binary_res$weiadj, 
                        beta = 1, 
                        transform = TRUE)
plot(lm17)
calculate_resilience(lm17)

set.seed(123456)
lm18 <- make_2d_Isingland(thresholds = manipulated_thresholds_resst_sui_sim18, 
                        weiadj = RESST_sui_binary_res$weiadj, 
                        beta = 1, 
                        transform = TRUE)

plot(lm18)
calculate_resilience(lm18)


set.seed(123456)
lm19 <- make_2d_Isingland(thresholds = manipulated_thresholds_resst_sui_sim19, 
                        weiadj = RESST_sui_binary_res$weiadj, 
                        beta = 1, 
                        transform = TRUE)

plot(lm19)
calculate_resilience(lm19)

set.seed(123456)
lm20 <- make_2d_Isingland(thresholds = manipulated_thresholds_resst_sui_sim20, 
                        weiadj = RESST_sui_binary_res$weiadj, 
                        beta = 1, 
                        transform = TRUE)

plot(lm20)
calculate_resilience(lm20)


set.seed(123456)
lm21 <- make_2d_Isingland(thresholds = manipulated_thresholds_resst_sui_sim21, 
                        weiadj = RESST_sui_binary_res$weiadj, 
                        beta = 1, 
                        transform = TRUE)

plot(lm21)
calculate_resilience(lm21)

## plot all images ##

add_title_and_remove_axes_labels <- function(plot_object, title) {
  plot_object +
    ggtitle(title) +
    theme(
      axis.title.x = element_blank(),
      axis.title.y = element_blank(),
      axis.text.x = element_blank(),
      axis.text.y = element_blank(),
      plot.title = element_text(family = "serif", size = 8, hjust = 0.5)
    )
}

# 3x7 
plot_grid(
  add_title_and_remove_axes_labels(plot(lm1), "Item 1"),
  add_title_and_remove_axes_labels(plot(lm2), "Item 2"),
  add_title_and_remove_axes_labels(plot(lm3), "Item 3"),
  add_title_and_remove_axes_labels(plot(lm4), "Item 4"),
  add_title_and_remove_axes_labels(plot(lm5), "Item 5"),
  add_title_and_remove_axes_labels(plot(lm6), "Item 6"),
  add_title_and_remove_axes_labels(plot(lm7), "Item 7"),
  
  add_title_and_remove_axes_labels(plot(lm8), "Item 8"),
  add_title_and_remove_axes_labels(plot(lm9), "Item 9"),
  add_title_and_remove_axes_labels(plot(lm10), "Item 10"),
  add_title_and_remove_axes_labels(plot(lm11), "Item 11"),
  add_title_and_remove_axes_labels(plot(lm12), "Item 12"),
  add_title_and_remove_axes_labels(plot(lm13), "Item 13"),
  add_title_and_remove_axes_labels(plot(lm14), "Item 14"),
  
  add_title_and_remove_axes_labels(plot(lm15), "Item 15"),
  add_title_and_remove_axes_labels(plot(lm16), "Item 16"),
  add_title_and_remove_axes_labels(plot(lm17), "Item 17"),
  add_title_and_remove_axes_labels(plot(lm18), "Item 18"),
  add_title_and_remove_axes_labels(plot(lm19), "Item 19"),
  add_title_and_remove_axes_labels(plot(lm20), "Item 20"),
  add_title_and_remove_axes_labels(plot(lm21), "Item 21"),
  
  ncol = 7
)
```

```{r S Ising model simulation}
## takes 2-5 HOURS to run ##

input <- list(graph = connectivity_resst_sui_sim, intercepts = thresholds_resst_sui_sim)

set.seed(123456)
Sim1 <- netSimulator(
  input = input,
  default = "IsingFit",  
  nCases = 274,
  nReps = 1000,
  nCores = 4 # use this to check how many you have available, and then /2 :parallel::detectCores()
)

Sim1
plot(Sim1)
plot(Sim1, 
     yvar="strength")
```

```{r S Model structure test}

LCT_recovery_sui <- LCT(
  RESST_sui_binary,
  corr = "auto", # tetrachoric (binary)
  model = "glasso",
  algorithm = "walktrap",
  uni.method = "Louvain", 
  iter = 100, # recommended
  seed = 123456,
  verbose = FALSE,
)

LCT_recovery_sui
```

### Former suicide group 

```{r NS Isolate variables}

RESST_no_sui_binary <- dplyr::select(RESST_sim_lifetime_risk_di, # binary vars
                              R1, 
                              R2, 
                              R3,
                              R4, 
                              R5, 
                              R6,
                              R7, 
                              R8, 
                              R9,
                              R10, 
                              R11, 
                              R12,
                              R13, 
                              R14, 
                              R15,
                              R16, 
                              R17, 
                              R18,
                              R19, 
                              R20, 
                              R21,
                              )
nrow(RESST_no_sui_binary)

write.csv(RESST_no_sui_binary, 'No_sui_data_output/DF_no_sui_data_371.csv') # csv with our final dataset

nodeNames = c( "R1_di","R2_di", "R3_di","R4_di", "R5_di", "R6_di","R7_di", "R8_di", "R9_di","R10_di", "R11_di","R12_di","R13_di","R14_di","R15_di","R16_di", "R17_di", "R18_di","R19_di", "R20_di", "R21_di")
```

```{r NS Ising model}

RESST_no_sui_binary <- IsingFit(RESST_no_sui_binary, plot = FALSE) 

sim_no_sui_base_ising <- qgraph(RESST_no_sui_binary$weiadj,
                     theme = "colorblind",
                     nodeNames = nodeNames,
                     label.norm = "OOO",
                     legend = FALSE,
                     border.width = as.numeric(abs(RESST_no_sui_binary$thresholds)*3),
                     border.color = "purple") #  Node borders show the preference of the  node to be present/absent. > thickness shows lower likelihood to activate.

### get connectivity and threshold objects -  to use these in  (1) case simulations -- equilibrium perturbed -- and (2) phase stability analysis ###

connectivity_resst_no_sui_sim = RESST_no_sui_binary$weiadj 
thresholds_resst_no_sui_sim = RESST_no_sui_binary$thresholds 

## save connectivities and thresholds as dataframes and then excel files 
# connectivities
DF_ising_ns_connectivities <- as.data.frame(connectivity_resst_no_sui_sim)

write.csv(DF_ising_ns_connectivities, 'No_sui_data_output/DF_no_sui_ising_connectivities.csv') # csv with ising model connectivities 
# save(DF_ising_connectivities, file="DF_ising_connectivities.Rdata") # Rdata file to directly import to R
## this saved our connectivies as Rdata

# thresholds
DF_ising_ns_thresholds <- as.data.frame(thresholds_resst_no_sui_sim)

write.csv(DF_ising_ns_thresholds, 'No_sui_data_output/DF_no sui_ising_thresholds.csv') # excel with ising model feature thresholds

# save(DF_ising_thresholds, file="DF_ising_thresholds.Rdata") # Rdata file to directly import to R
## this saved our thresholds as Rdata

# save image of ising model
# pdf("sim_sui_base_ising", width=10, height=10)
# plot(sim_sui_base_ising)
# dev.off()

# view 
DF_ising_ns_connectivities
DF_ising_ns_thresholds
```
```{r NS Simulate equilibrium}
set.seed(123456)
Ntime = 20000 # 20,000 time points to simulate

Glauber_2(connectivity_resst_no_sui_sim, thresholds_resst_no_sui_sim, Ntime, beta = 1.5, intervention = "positive") 
Equilibrium_no_sui <- output.binary_eq 
Pertubations_no_sui <- output.binary_pert
stateEQ_no_sui <- mean(apply(Equilibrium_no_sui,1,sum)) # mean sum of active symptoms at equilibrium 
statePERT_no_sui <- mean(apply(Pertubations_no_sui,1,sum))  # mean sum of active symptoms at with perturbations 

stateEQ_no_sui_sd <- sd(apply(Equilibrium_no_sui,1,sum)) # sd of sum of active symptoms at equilibrium 
statePERT_no_sui_sd <- sd(apply(Pertubations_no_sui,1,sum)) # sd of sum of active symptoms at with perturbations

stateEQ_no_sui # 17.67815
statePERT_no_sui # 15.2466
stateEQ_no_sui_sd  # 2.6569
statePERT_no_sui_sd  # 4.334112

# make dataframe with total active nodes at equilibrium and with perturbations at all timepoints (20,000)
DF_simulations_no_sui <- data.frame(Timepoints = 1:Ntime,
                         Equilibrium = apply(Equilibrium_no_sui,1,sum),
                         Perturbations = apply(Pertubations_no_sui,1,sum)) 

data.frame(DF_simulations_no_sui)

summary(DF_simulations_no_sui) # look at median and interquartile range 
#  Timepoints     Equilibrium    Perturbations  
# Min.   :    1   Min.   : 7.00   Min.   : 0.00  
# 1st Qu.: 5001   1st Qu.:16.00   1st Qu.:13.00  
# Median :10000   Median :19.00   Median :15.00  
# Mean   :10000   Mean   :17.68   Mean   :15.25  
# 3rd Qu.:15000   3rd Qu.:20.00   3rd Qu.:19.00  
# Max.   :20000   Max.   :21.00   Max.   :21.00 

DF_subset_1_2k_ns <- subset(DF_simulations_no_sui, Timepoints >= 1000 & Timepoints <= 2000)
summary(DF_subset_1_2k_ns) # this is 1-2000 timepoints
# Timepoints    Equilibrium    Perturbations  
# Min.   :1000   Min.   :17.00   Min.   : 0.00  
# 1st Qu.:1250   1st Qu.:19.00   1st Qu.:15.00  
# Median :1500   Median :19.00   Median :17.00  
# Mean   :1500   Mean   :19.45   Mean   :16.08  
# 3rd Qu.:1750   3rd Qu.:20.00   3rd Qu.:19.00  
# Max.   :2000   Max.   :21.00   Max.   :20.00 
Pertubations_sui_1_2k_ns <- Pertubations_no_sui[1000:2000, ]
Pertubations_PERT_sui_1_2k_mean_ns <- mean(apply(Pertubations_sui_1_2k_ns,1,sum)) 
Pertubations_PERT_sui_1_2k_sd_ns <- sd(apply(Pertubations_sui_1_2k_ns,1,sum)) 
Pertubations_PERT_sui_1_2k_mean_ns # mean =  16.07592 (same as above described in IQR)
Pertubations_PERT_sui_1_2k_sd_ns # SD = 3.469615

DF_subset_2_3k_ns <- subset(DF_simulations_no_sui, Timepoints >= 2000 & Timepoints <= 3000)
summary(DF_subset_2_3k_ns) # this is 2-3000 timepoints
# Timepoints    Equilibrium    Perturbations  
# Min.   :2000   Min.   :10.00   Min.   : 0.00  
# 1st Qu.:2250   1st Qu.:15.00   1st Qu.:16.00  
# Median :2500   Median :19.00   Median :19.00  
# Mean   :2500   Mean   :17.61   Mean   :17.84  
# 3rd Qu.:2750   3rd Qu.:20.00   3rd Qu.:20.00  
# Max.   :3000   Max.   :21.00   Max.   :21.00  
Pertubations_sui_2_3k_ns <- Pertubations_no_sui[2000:3000, ]
Pertubations_PERT_sui_2_3k_mean_ns <- mean(apply(Pertubations_sui_2_3k_ns,1,sum)) 
Pertubations_PERT_sui_2_3k_sd_ns <- sd(apply(Pertubations_sui_2_3k_ns,1,sum)) 
Pertubations_PERT_sui_2_3k_mean_ns # mean = 17.84116 (same as above described in IQR)
Pertubations_PERT_sui_2_3k_sd_ns # SD 3.520191


# plot density (active sum density) at equilibrium and with perturbation

# individual plots
ggplot(data = DF_simulations_no_sui) + geom_density(aes(x=Equilibrium) , fill = "#00AFBB")
ggplot(data = DF_simulations_no_sui) + geom_density(aes(x=Perturbations) , fill = "#00AFBB")

# combined plot
# change some default settings 
ggplot(data = DF_simulations_no_sui) +
  geom_density(aes(x = Equilibrium, fill = "Equilibrium"), alpha = 0.5) +
  geom_density(aes(x = Perturbations, fill = "Perturbations"), alpha = 0.5) +
  scale_fill_manual(values = c("#838B8B", "#C1CDCD"), name = "") +
  labs(title = "", 
       x = "Active symptoms over 20,000 timepoints", 
       y = "Density") +
  theme(panel.background = element_rect(fill = "white"),
        panel.grid.major = element_line(color = "grey", linetype = "dashed"),
        panel.grid.minor = element_line(color = "grey", linetype = "dashed"),
        text=element_text(size = 14,  family = "serif"))

## save Rdata/excel dataframes ##

# active node totals at equilibrium and with perturbations
write.csv(DF_simulations_no_sui, "No_sui_data_output/DF_no_sui_simulations.csv") 

# raw simulated data at equilibrium (n = 20,000 for 21 variables)
Equilibrium_no_sui <- as.data.frame(Equilibrium_no_sui)
write.csv(Equilibrium_no_sui, "No_sui_data_output/DF_no_sui_equilibrium.csv")

# raw simulated data with perturbations (n = 20,000 for 21 variables)
Pertubations_no_sui <- as.data.frame(Pertubations_no_sui)
write.csv(Pertubations_no_sui, "No_sui_data_output/DF_no_sui_perturbations.csv")
```
```{r NS simulation plots}

# equilibrium #
ggplot(DF_simulations_no_sui, # load 
       aes(x = Timepoints, y = Equilibrium)) + 
  geom_line() +
  theme_classic() +
  labs(title = "", 
       x = "Time points",
       y = expression(paste("RESST symptoms - FSA"))) +
  theme(
    plot.title = element_text(size = 14, face="bold", hjust = 0.5),
    axis.title = element_text(size=12, face = "bold"),
    axis.text = element_text(size = 12, face = "bold")) 

hist(DF_simulations_no_sui$Equilibrium,
     col="black",
     xlim=c(0,21),
     breaks=seq(0,21),
     main="",
     xlab = expression(bold("Symptoms")),
     ylab = expression(bold(paste("RESST symptoms"))))

# perturbations #
ggplot(DF_simulations_no_sui, aes(x = Timepoints, y = Perturbations)) + 
  geom_line() +
  theme_classic() +
  geom_vline(xintercept = seq(from = 1000, to = Ntime -1, by=1000), color="red", 
             size=.7) +
  labs(title = "", 
       x = "Time points",
       y = expression(paste("RESST symptoms"))) +
  theme(
    plot.title = element_text(size = 14, face="bold", hjust = 0.5),
    axis.title = element_text(size=12, face = "bold"),
    axis.text = element_text(size = 12, face = "bold")) 

# plot perturbed time 2,000 - 3,000 (close up of full)
ggplot(DF_simulations_no_sui, aes(x = Timepoints, y = Perturbations)) + 
  geom_line() +
  theme_classic() +
  geom_vline(xintercept = seq(from = 1000, to = Ntime -1, by=1000), color="red", 
             size=.7) +
  labs(title = "", 
       x = "Time points",
       y = expression(paste("RESST symptoms"))) +
  theme(
    plot.title = element_text(size = 14, face="bold", hjust = 0.5),
    axis.title = element_text(size=12, face = "bold"),
    axis.text = element_text(size = 12, face = "bold")) + scale_x_continuous(limits = c(2000, 3000))

# plot perturbed time 1,000 - 2,000 (cloe up of full)
ggplot(DF_simulations_no_sui, aes(x = Timepoints, y = Perturbations)) + 
  geom_line() +
  theme_classic() +
  geom_vline(xintercept = seq(from = 1000, to = Ntime -1, by=1000), color="red", 
             size=.7) +
  labs(title = "", 
       x = "Time points",
       y = expression(paste("RESST symptoms"))) +
  theme(
    plot.title = element_text(size = 14, face="bold", hjust = 0.5),
    axis.title = element_text(size=12, face = "bold"),
    axis.text = element_text(size = 12, face = "bold")) + scale_x_continuous(limits = c(1000, 2000))

hist(DF_simulations_no_sui$Perturbations,
     col="black",
     xlim=c(0,21),
     breaks=seq(0,21),
     main="",
     xlab = expression(bold("Symptoms")),
     ylab = expression(bold(paste("RESST symptoms"))))
```
```{r NS system activity preference}
# connectivity_resst_no_sui_sim = RESST_sui_binary_res$weiadj 
# thresholds_resst_no_sui_sim = RESST_sui_binary_res$thresholds 
set.seed(123456)
l2 <- make_2d_Isingland(thresholds = RESST_no_sui_binary_res$thresholds, 
                        weiadj = RESST_no_sui_binary_res$weiadj, 
                        beta = 1, 
                        transform = TRUE)

plot(l2)
calculate_resilience(l2)

# ggsave("./original_network_resilience_NO_suicide.png", plot(l2) + autolayer(calculate_resilience(l2)), width = 8, height = 6)

```

```{r NS simulations INDIVIDUAL item manipulations}
## we are manipulating each symptom by 2 SD - to prefer to be more present, THEN, run at equilibrium with glaubers dynamics ##

# I can't get a loop to work without incorporating the previous manipulation in the following one, so just doing them individually 

amount_of_SDs_perturbation = 2

# DF_ising_thresholds_no_sui -- thresholds


# Manipulate item 1's threshold
manipulated_thresholds_resst_no_sui_sim1 <- thresholds_resst_no_sui_sim
manipulated_thresholds_resst_no_sui_sim1[1] <- manipulated_thresholds_resst_no_sui_sim1[1] - amount_of_SDs_perturbation * sd(thresholds_resst_no_sui_sim)
print(manipulated_thresholds_resst_no_sui_sim1) # -6.17752238 

# Manipulate item 2's threshold
manipulated_thresholds_resst_no_sui_sim2 <- thresholds_resst_no_sui_sim
manipulated_thresholds_resst_no_sui_sim2[2] <- manipulated_thresholds_resst_no_sui_sim2[2] - amount_of_SDs_perturbation * sd(thresholds_resst_no_sui_sim)
print(manipulated_thresholds_resst_no_sui_sim2) # -5.14435400 

# Manipulate item 3's threshold
manipulated_thresholds_resst_no_sui_sim3 <- thresholds_resst_no_sui_sim
manipulated_thresholds_resst_no_sui_sim3[3] <- manipulated_thresholds_resst_no_sui_sim3[3] - amount_of_SDs_perturbation * sd(thresholds_resst_no_sui_sim)
print(manipulated_thresholds_resst_no_sui_sim3) # -3.21295938

# Manipulate item 4's threshold
manipulated_thresholds_resst_no_sui_sim4 <- thresholds_resst_no_sui_sim
manipulated_thresholds_resst_no_sui_sim4[4] <- manipulated_thresholds_resst_no_sui_sim4[4] - amount_of_SDs_perturbation * sd(thresholds_resst_no_sui_sim)
print(manipulated_thresholds_resst_no_sui_sim4) 

# Manipulate item 5's threshold
manipulated_thresholds_resst_no_sui_sim5 <- thresholds_resst_no_sui_sim
manipulated_thresholds_resst_no_sui_sim5[5] <- manipulated_thresholds_resst_no_sui_sim5[5] - amount_of_SDs_perturbation * sd(thresholds_resst_no_sui_sim)
print(manipulated_thresholds_resst_no_sui_sim5) 

# Manipulate item 6's threshold
manipulated_thresholds_resst_no_sui_sim6 <- thresholds_resst_no_sui_sim
manipulated_thresholds_resst_no_sui_sim6[6] <- manipulated_thresholds_resst_no_sui_sim6[6] - amount_of_SDs_perturbation * sd(thresholds_resst_no_sui_sim)
print(manipulated_thresholds_resst_no_sui_sim6)

# Manipulate item 7's threshold
manipulated_thresholds_resst_no_sui_sim7 <- thresholds_resst_no_sui_sim
manipulated_thresholds_resst_no_sui_sim7[7] <- manipulated_thresholds_resst_no_sui_sim7[7] - amount_of_SDs_perturbation * sd(thresholds_resst_no_sui_sim)
print(manipulated_thresholds_resst_no_sui_sim7) 

# Manipulate item 8's threshold
manipulated_thresholds_resst_no_sui_sim8 <- thresholds_resst_no_sui_sim
manipulated_thresholds_resst_no_sui_sim8[8] <- manipulated_thresholds_resst_no_sui_sim8[8] - amount_of_SDs_perturbation * sd(thresholds_resst_no_sui_sim)
print(manipulated_thresholds_resst_no_sui_sim8) 

# Manipulate item 9's threshold
manipulated_thresholds_resst_no_sui_sim9 <- thresholds_resst_no_sui_sim
manipulated_thresholds_resst_no_sui_sim9[9] <- manipulated_thresholds_resst_no_sui_sim9[9] - amount_of_SDs_perturbation * sd(thresholds_resst_no_sui_sim)
print(manipulated_thresholds_resst_no_sui_sim9) 

# Manipulate item 10's threshold
manipulated_thresholds_resst_no_sui_sim10 <- thresholds_resst_no_sui_sim
manipulated_thresholds_resst_no_sui_sim10[10] <- manipulated_thresholds_resst_no_sui_sim10[10] - amount_of_SDs_perturbation * sd(thresholds_resst_no_sui_sim)
print(manipulated_thresholds_resst_no_sui_sim10) 

# Manipulate item 11's threshold
manipulated_thresholds_resst_no_sui_sim11 <- thresholds_resst_no_sui_sim
manipulated_thresholds_resst_no_sui_sim11[11] <- manipulated_thresholds_resst_no_sui_sim11[11] - amount_of_SDs_perturbation * sd(thresholds_resst_no_sui_sim)
print(manipulated_thresholds_resst_no_sui_sim11) 

# Manipulate item 12's threshold
manipulated_thresholds_resst_no_sui_sim12 <- thresholds_resst_no_sui_sim
manipulated_thresholds_resst_no_sui_sim12[12] <- manipulated_thresholds_resst_no_sui_sim12[12] - amount_of_SDs_perturbation * sd(thresholds_resst_no_sui_sim)
print(manipulated_thresholds_resst_no_sui_sim12) 

# Manipulate item 13's threshold
manipulated_thresholds_resst_no_sui_sim13 <- thresholds_resst_no_sui_sim
manipulated_thresholds_resst_no_sui_sim13[13] <- manipulated_thresholds_resst_no_sui_sim13[13] - amount_of_SDs_perturbation * sd(thresholds_resst_no_sui_sim)
print(manipulated_thresholds_resst_no_sui_sim13) 

# Manipulate item 14's threshold
manipulated_thresholds_resst_no_sui_sim14 <- thresholds_resst_no_sui_sim
manipulated_thresholds_resst_no_sui_sim14[14] <- manipulated_thresholds_resst_no_sui_sim14[14] - amount_of_SDs_perturbation * sd(thresholds_resst_no_sui_sim)
print(manipulated_thresholds_resst_no_sui_sim14) 

# Manipulate item 15's threshold
manipulated_thresholds_resst_no_sui_sim15 <- thresholds_resst_no_sui_sim
manipulated_thresholds_resst_no_sui_sim15[15] <- manipulated_thresholds_resst_no_sui_sim15[15] - amount_of_SDs_perturbation * sd(thresholds_resst_no_sui_sim)
print(manipulated_thresholds_resst_no_sui_sim15) 

# Manipulate item 16's threshold
manipulated_thresholds_resst_no_sui_sim16 <- thresholds_resst_no_sui_sim
manipulated_thresholds_resst_no_sui_sim16[16] <- manipulated_thresholds_resst_no_sui_sim16[16] - amount_of_SDs_perturbation * sd(thresholds_resst_no_sui_sim)
print(manipulated_thresholds_resst_no_sui_sim16) 

# Manipulate item 17's threshold
manipulated_thresholds_resst_no_sui_sim17 <- thresholds_resst_no_sui_sim
manipulated_thresholds_resst_no_sui_sim17[17] <- manipulated_thresholds_resst_no_sui_sim17[17] - amount_of_SDs_perturbation * sd(thresholds_resst_no_sui_sim)
print(manipulated_thresholds_resst_no_sui_sim17)

# Manipulate item 18's threshold
manipulated_thresholds_resst_no_sui_sim18 <- thresholds_resst_no_sui_sim
manipulated_thresholds_resst_no_sui_sim18[18] <- manipulated_thresholds_resst_no_sui_sim18[18] - amount_of_SDs_perturbation * sd(thresholds_resst_no_sui_sim)
print(manipulated_thresholds_resst_no_sui_sim18) 

# Manipulate item 19's threshold
manipulated_thresholds_resst_no_sui_sim19 <- thresholds_resst_no_sui_sim
manipulated_thresholds_resst_no_sui_sim19[19] <- manipulated_thresholds_resst_no_sui_sim19[19] - amount_of_SDs_perturbation * sd(thresholds_resst_no_sui_sim)
print(manipulated_thresholds_resst_no_sui_sim19)

# Manipulate item 20's threshold
manipulated_thresholds_resst_no_sui_sim20 <- thresholds_resst_no_sui_sim
manipulated_thresholds_resst_no_sui_sim20[20] <- manipulated_thresholds_resst_no_sui_sim20[20] - amount_of_SDs_perturbation * sd(thresholds_resst_no_sui_sim)

print(manipulated_thresholds_resst_no_sui_sim20) 

# Manipulate item 21's threshold
manipulated_thresholds_resst_no_sui_sim21 <- thresholds_resst_no_sui_sim
manipulated_thresholds_resst_no_sui_sim21[21] <- manipulated_thresholds_resst_no_sui_sim21[21] - amount_of_SDs_perturbation * sd(thresholds_resst_no_sui_sim)

print(manipulated_thresholds_resst_no_sui_sim21) 


# equilbrium with item 1 manipulated #
set.seed(123456)
Glauber_1(connectivity_resst_no_sui_sim, manipulated_thresholds_resst_no_sui_sim1, Ntime = 20000, beta = 1.5)

Equilibrium_no_sui_1_manip <- output.binary_eq 
Equilibrium_no_sui_1_manip
stateEQ_no_sui_1_manip <- mean(apply(Equilibrium_no_sui_1_manip,1,sum)) 
stateEQ_no_sui_1_manip # 15.3789
stateEQ_no_sui_1_manip_sd <- sd(apply(Equilibrium_no_sui_1_manip,1,sum)) 
stateEQ_no_sui_1_manip_sd # 2.187253

# equilbrium with item 2 manipulated #
set.seed(123456)
Glauber_1(connectivity_resst_no_sui_sim, manipulated_thresholds_resst_no_sui_sim2, Ntime = 20000, beta = 1.5)

Equilibrium_no_sui_2_manip <- output.binary_eq 
Equilibrium_no_sui_2_manip
stateEQ_no_sui_2_manip <- mean(apply(Equilibrium_no_sui_2_manip,1,sum)) 
stateEQ_no_sui_2_manip # 14.58515
stateEQ_no_sui_2_manip_sd <- sd(apply(Equilibrium_no_sui_2_manip,1,sum)) 
stateEQ_no_sui_2_manip_sd # 1.998412

# equilbrium with item 3 manipulated #
set.seed(123456)
Glauber_1(connectivity_resst_no_sui_sim, manipulated_thresholds_resst_no_sui_sim3, Ntime = 20000, beta = 1.5)

Equilibrium_no_sui_3_manip <- output.binary_eq 
Equilibrium_no_sui_3_manip
stateEQ_no_sui_3_manip <- mean(apply(Equilibrium_no_sui_3_manip,1,sum)) 
stateEQ_no_sui_3_manip # 14.3734
stateEQ_no_sui_3_manip_sd <- sd(apply(Equilibrium_no_sui_3_manip,1,sum)) 
stateEQ_no_sui_3_manip_sd # 2.236945

# equilbrium with item 4 manipulated #
set.seed(123456)
Glauber_1(connectivity_resst_no_sui_sim, manipulated_thresholds_resst_no_sui_sim4, Ntime = 20000, beta = 1.5)

Equilibrium_no_sui_4_manip <- output.binary_eq 
Equilibrium_no_sui_4_manip
stateEQ_no_sui_4_manip <- mean(apply(Equilibrium_no_sui_4_manip,1,sum)) 
stateEQ_no_sui_4_manip # 15.51845
stateEQ_no_sui_4_manip_sd <- sd(apply(Equilibrium_no_sui_4_manip,1,sum)) 
stateEQ_no_sui_4_manip_sd # 2.741612

# equilbrium with item 5 manipulated #
set.seed(123456)
Glauber_1(connectivity_resst_no_sui_sim, manipulated_thresholds_resst_no_sui_sim5, Ntime = 20000, beta = 1.5)

Equilibrium_no_sui_5_manip <- output.binary_eq 
Equilibrium_no_sui_5_manip
stateEQ_no_sui_5_manip <- mean(apply(Equilibrium_no_sui_5_manip,1,sum)) 
stateEQ_no_sui_5_manip # 14.41725
stateEQ_no_sui_5_manip_sd <- sd(apply(Equilibrium_no_sui_5_manip,1,sum)) 
stateEQ_no_sui_5_manip_sd # 1.662405

# equilbrium with item 6 manipulated #
set.seed(123456)
Glauber_1(connectivity_resst_no_sui_sim, manipulated_thresholds_resst_no_sui_sim6, Ntime = 20000, beta = 1.5)

Equilibrium_no_sui_6_manip <- output.binary_eq 
Equilibrium_no_sui_6_manip
stateEQ_no_sui_6_manip <- mean(apply(Equilibrium_no_sui_6_manip,1,sum)) 
stateEQ_no_sui_6_manip # 14.9372
stateEQ_no_sui_6_manip_sd <- sd(apply(Equilibrium_no_sui_6_manip,1,sum)) 
stateEQ_no_sui_6_manip_sd # 2.024145

# equilbrium with item 7 manipulated #
set.seed(123456)
Glauber_1(connectivity_resst_no_sui_sim, manipulated_thresholds_resst_no_sui_sim7, Ntime = 20000, beta = 1.5)

Equilibrium_no_sui_7_manip <- output.binary_eq 
Equilibrium_no_sui_7_manip
stateEQ_no_sui_7_manip <- mean(apply(Equilibrium_no_sui_7_manip,1,sum)) 
stateEQ_no_sui_7_manip # 15.1213
stateEQ_no_sui_7_manip_sd <- sd(apply(Equilibrium_no_sui_7_manip,1,sum)) 
stateEQ_no_sui_7_manip_sd # 2.187767

# equilbrium with item 8 manipulated #
set.seed(123456)
Glauber_1(connectivity_resst_no_sui_sim, manipulated_thresholds_resst_no_sui_sim8, Ntime = 20000, beta = 1.5)

Equilibrium_no_sui_8_manip <- output.binary_eq 
Equilibrium_no_sui_8_manip
stateEQ_no_sui_8_manip <- mean(apply(Equilibrium_no_sui_8_manip,1,sum)) 
stateEQ_no_sui_8_manip # 14.2807
stateEQ_no_sui_8_manip_sd <- sd(apply(Equilibrium_no_sui_8_manip,1,sum)) 
stateEQ_no_sui_8_manip_sd # 2.731406

# equilbrium with item 9 manipulated #
set.seed(123456)
Glauber_1(connectivity_resst_no_sui_sim, manipulated_thresholds_resst_no_sui_sim9, Ntime = 20000, beta = 1.5)

Equilibrium_no_sui_9_manip <- output.binary_eq 
Equilibrium_no_sui_9_manip
stateEQ_no_sui_9_manip <- mean(apply(Equilibrium_no_sui_9_manip,1,sum)) 
stateEQ_no_sui_9_manip # 15.4353
stateEQ_no_sui_9_manip_sd <- sd(apply(Equilibrium_no_sui_9_manip,1,sum)) 
stateEQ_no_sui_9_manip_sd # 3.148239

# equilbrium with item 10 manipulated #
set.seed(123456)
Glauber_1(connectivity_resst_no_sui_sim, manipulated_thresholds_resst_no_sui_sim10, Ntime = 20000, beta = 1.5)

Equilibrium_no_sui_10_manip <- output.binary_eq 
Equilibrium_no_sui_10_manip
stateEQ_no_sui_10_manip <- mean(apply(Equilibrium_no_sui_10_manip,1,sum)) 
stateEQ_no_sui_10_manip # 17.2273
stateEQ_no_sui_10_manip_sd <- sd(apply(Equilibrium_no_sui_10_manip,1,sum)) 
stateEQ_no_sui_10_manip_sd # 2.768252

# equilbrium with item 11 manipulated #
set.seed(123456)
Glauber_1(connectivity_resst_no_sui_sim, manipulated_thresholds_resst_no_sui_sim11, Ntime = 20000, beta = 1.5) 

Equilibrium_no_sui_11_manip <- output.binary_eq 
Equilibrium_no_sui_11_manip
stateEQ_no_sui_11_manip <- mean(apply(Equilibrium_no_sui_11_manip,1,sum)) 
stateEQ_no_sui_11_manip # 17.06995
stateEQ_no_sui_11_manip_sd <- sd(apply(Equilibrium_no_sui_11_manip,1,sum)) 
stateEQ_no_sui_11_manip_sd # 2.554855

# equilbrium with item 12 manipulated #
set.seed(123456)
Glauber_1(connectivity_resst_no_sui_sim, manipulated_thresholds_resst_no_sui_sim12, Ntime = 20000, beta = 1.5) 

Equilibrium_no_sui_12_manip <- output.binary_eq 
Equilibrium_no_sui_12_manip
stateEQ_no_sui_12_manip <- mean(apply(Equilibrium_no_sui_12_manip,1,sum)) 
stateEQ_no_sui_12_manip # 16.38855
stateEQ_no_sui_12_manip_sd <- sd(apply(Equilibrium_no_sui_12_manip,1,sum)) 
stateEQ_no_sui_12_manip_sd # 3.085118

# equilbrium with item 13 manipulated #
set.seed(123456)
Glauber_1(connectivity_resst_no_sui_sim, manipulated_thresholds_resst_no_sui_sim13, Ntime = 20000, beta = 1.5) 

Equilibrium_no_sui_13_manip <- output.binary_eq 
Equilibrium_no_sui_13_manip
stateEQ_no_sui_13_manip <- mean(apply(Equilibrium_no_sui_13_manip,1,sum)) 
stateEQ_no_sui_13_manip # 15.86125
stateEQ_no_sui_13_manip_sd <- sd(apply(Equilibrium_no_sui_13_manip,1,sum)) 
stateEQ_no_sui_13_manip_sd # 3.082495

# equilbrium with item 14 manipulated #
set.seed(123456)
Glauber_1(connectivity_resst_no_sui_sim, manipulated_thresholds_resst_no_sui_sim14, Ntime = 20000, beta = 1.5)

Equilibrium_no_sui_14_manip <- output.binary_eq 
Equilibrium_no_sui_14_manip
stateEQ_no_sui_14_manip <- mean(apply(Equilibrium_no_sui_14_manip,1,sum)) 
stateEQ_no_sui_14_manip # 15.9262
stateEQ_no_sui_14_manip_sd <- sd(apply(Equilibrium_no_sui_14_manip,1,sum)) 
stateEQ_no_sui_14_manip_sd # 3.224837

# equilbrium with item 15 manipulated #
set.seed(123456)
Glauber_1(connectivity_resst_no_sui_sim, manipulated_thresholds_resst_no_sui_sim15, Ntime = 20000, beta = 1.5) 

Equilibrium_no_sui_15_manip <- output.binary_eq 
Equilibrium_no_sui_15_manip
stateEQ_no_sui_15_manip <- mean(apply(Equilibrium_no_sui_15_manip,1,sum)) 
stateEQ_no_sui_15_manip # 16.46625
stateEQ_no_sui_15_manip_sd <- sd(apply(Equilibrium_no_sui_15_manip,1,sum)) 
stateEQ_no_sui_15_manip_sd # 3.240955

# equilbrium with item 16 manipulated #
set.seed(123456)
Glauber_1(connectivity_resst_no_sui_sim, manipulated_thresholds_resst_no_sui_sim16, Ntime = 20000, beta = 1.5) 

Equilibrium_no_sui_16_manip <- output.binary_eq 
Equilibrium_no_sui_16_manip
stateEQ_no_sui_16_manip <- mean(apply(Equilibrium_no_sui_16_manip,1,sum)) 
stateEQ_no_sui_16_manip # 16.29145
stateEQ_no_sui_16_manip_sd <- sd(apply(Equilibrium_no_sui_16_manip,1,sum)) 
stateEQ_no_sui_16_manip_sd # 3.110915

# equilbrium with item 17 manipulated #
set.seed(123456)
Glauber_1(connectivity_resst_no_sui_sim, manipulated_thresholds_resst_no_sui_sim17, Ntime = 20000, beta = 1.5) 

Equilibrium_no_sui_17_manip <- output.binary_eq 
Equilibrium_no_sui_17_manip
stateEQ_no_sui_17_manip <- mean(apply(Equilibrium_no_sui_17_manip,1,sum)) 
stateEQ_no_sui_17_manip # 16.11475
stateEQ_no_sui_17_manip_sd <- sd(apply(Equilibrium_no_sui_17_manip,1,sum)) 
stateEQ_no_sui_17_manip_sd # 3.320336

# equilbrium with item 18 manipulated #
set.seed(123456)
Glauber_1(connectivity_resst_no_sui_sim, manipulated_thresholds_resst_no_sui_sim18, Ntime = 20000, beta = 1.5) 

Equilibrium_no_sui_18_manip <- output.binary_eq 
Equilibrium_no_sui_18_manip
stateEQ_no_sui_18_manip <- mean(apply(Equilibrium_no_sui_18_manip,1,sum)) 
stateEQ_no_sui_18_manip #  16.7736
stateEQ_no_sui_18_manip_sd <- sd(apply(Equilibrium_no_sui_18_manip,1,sum)) 
stateEQ_no_sui_18_manip_sd # 2.963643

# equilbrium with item 19 manipulated #
set.seed(123456)
Glauber_1(connectivity_resst_no_sui_sim, manipulated_thresholds_resst_no_sui_sim19, Ntime = 20000, beta = 1.5) 

Equilibrium_no_sui_19_manip <- output.binary_eq 
Equilibrium_no_sui_19_manip
stateEQ_no_sui_19_manip <- mean(apply(Equilibrium_no_sui_19_manip,1,sum)) 
stateEQ_no_sui_19_manip # 17.03995
stateEQ_no_sui_19_manip_sd <- sd(apply(Equilibrium_no_sui_19_manip,1,sum)) 
stateEQ_no_sui_19_manip_sd # 2.757886

# equilbrium with item 20 manipulated #
set.seed(123456)
Glauber_1(connectivity_resst_no_sui_sim, manipulated_thresholds_resst_no_sui_sim20, Ntime = 20000, beta = 1.5)

Equilibrium_no_sui_20_manip <- output.binary_eq 
Equilibrium_no_sui_20_manip
stateEQ_no_sui_20_manip <- mean(apply(Equilibrium_no_sui_20_manip,1,sum)) 
stateEQ_no_sui_20_manip # 16.55895
stateEQ_no_sui_20_manip_sd <- sd(apply(Equilibrium_no_sui_20_manip,1,sum)) 
stateEQ_no_sui_20_manip_sd # 2.967013

# equilbrium with item 21 manipulated #
set.seed(123456)
Glauber_1(connectivity_resst_no_sui_sim, manipulated_thresholds_resst_no_sui_sim21, Ntime = 20000, beta = 1.5)

Equilibrium_no_sui_21_manip <- output.binary_eq 
Equilibrium_no_sui_21_manip
stateEQ_no_sui_21_manip <- mean(apply(Equilibrium_no_sui_21_manip,1,sum)) 
stateEQ_no_sui_21_manip # 15.0522
stateEQ_no_sui_21_manip_sd <- sd(apply(Equilibrium_no_sui_21_manip,1,sum)) 
stateEQ_no_sui_21_manip_sd # 2.812325

## dataframes with totals for each glauber simulation ##

DF_simulations_no_sui_1m <- data.frame(Timepoints = 1:Ntime,
                         Equilibrium = apply(Equilibrium_no_sui_1_manip,1,sum)) 

DF_simulations_no_sui_2m <- data.frame(Timepoints = 1:Ntime,
                         Equilibrium = apply(Equilibrium_no_sui_2_manip,1,sum)) 

DF_simulations_no_sui_3m <- data.frame(Timepoints = 1:Ntime,
                         Equilibrium = apply(Equilibrium_no_sui_3_manip,1,sum)) 

DF_simulations_no_sui_4m <- data.frame(Timepoints = 1:Ntime,
                         Equilibrium = apply(Equilibrium_no_sui_4_manip,1,sum)) 

DF_simulations_no_sui_5m <- data.frame(Timepoints = 1:Ntime,
                         Equilibrium = apply(Equilibrium_no_sui_5_manip,1,sum)) 

DF_simulations_no_sui_6m <- data.frame(Timepoints = 1:Ntime,
                         Equilibrium = apply(Equilibrium_no_sui_6_manip,1,sum)) 

DF_simulations_no_sui_7m <- data.frame(Timepoints = 1:Ntime,
                         Equilibrium = apply(Equilibrium_no_sui_7_manip,1,sum)) 

DF_simulations_no_sui_8m <- data.frame(Timepoints = 1:Ntime,
                         Equilibrium = apply(Equilibrium_no_sui_8_manip,1,sum)) 

DF_simulations_no_sui_9m <- data.frame(Timepoints = 1:Ntime,
                         Equilibrium = apply(Equilibrium_no_sui_9_manip,1,sum)) 

DF_simulations_no_sui_10m <- data.frame(Timepoints = 1:Ntime,
                         Equilibrium = apply(Equilibrium_no_sui_10_manip,1,sum)) 

DF_simulations_no_sui_11m <- data.frame(Timepoints = 1:Ntime,
                         Equilibrium = apply(Equilibrium_no_sui_11_manip,1,sum)) 

DF_simulations_no_sui_12m <- data.frame(Timepoints = 1:Ntime,
                         Equilibrium = apply(Equilibrium_no_sui_12_manip,1,sum)) 

DF_simulations_no_sui_13m <- data.frame(Timepoints = 1:Ntime,
                         Equilibrium = apply(Equilibrium_no_sui_13_manip,1,sum)) 

DF_simulations_no_sui_14m <- data.frame(Timepoints = 1:Ntime,
                         Equilibrium = apply(Equilibrium_no_sui_14_manip,1,sum)) 

DF_simulations_no_sui_15m <- data.frame(Timepoints = 1:Ntime,
                         Equilibrium = apply(Equilibrium_no_sui_15_manip,1,sum)) 

DF_simulations_no_sui_16m <- data.frame(Timepoints = 1:Ntime,
                         Equilibrium = apply(Equilibrium_no_sui_16_manip,1,sum)) 

DF_simulations_no_sui_17m <- data.frame(Timepoints = 1:Ntime,
                         Equilibrium = apply(Equilibrium_no_sui_17_manip,1,sum)) 

DF_simulations_no_sui_18m <- data.frame(Timepoints = 1:Ntime,
                         Equilibrium = apply(Equilibrium_no_sui_18_manip,1,sum)) 

DF_simulations_no_sui_19m <- data.frame(Timepoints = 1:Ntime,
                         Equilibrium = apply(Equilibrium_no_sui_19_manip,1,sum)) 

DF_simulations_no_sui_20m <- data.frame(Timepoints = 1:Ntime,
                         Equilibrium = apply(Equilibrium_no_sui_20_manip,1,sum)) 

DF_simulations_no_sui_21m <- data.frame(Timepoints = 1:Ntime,
                         Equilibrium = apply(Equilibrium_no_sui_21_manip,1,sum))

# IQR, range, mdn #
summ_1m_no_sui <- summary(DF_simulations_no_sui_1m$Equilibrium)
summ_2m_no_sui <- summary(DF_simulations_no_sui_2m$Equilibrium)
summ_3m_no_sui <- summary(DF_simulations_no_sui_3m$Equilibrium)
summ_4m_no_sui <- summary(DF_simulations_no_sui_4m$Equilibrium)
summ_5m_no_sui <- summary(DF_simulations_no_sui_5m$Equilibrium)
summ_6m_no_sui <- summary(DF_simulations_no_sui_6m$Equilibrium)
summ_7m_no_sui <- summary(DF_simulations_no_sui_7m$Equilibrium)
summ_8m_no_sui <- summary(DF_simulations_no_sui_8m$Equilibrium)
summ_9m_no_sui <- summary(DF_simulations_no_sui_9m$Equilibrium)
summ_10m_no_sui <- summary(DF_simulations_no_sui_10m$Equilibrium)
summ_11m_no_sui <- summary(DF_simulations_no_sui_11m$Equilibrium)
summ_12m_no_sui <- summary(DF_simulations_no_sui_12m$Equilibrium)
summ_13m_no_sui <- summary(DF_simulations_no_sui_13m$Equilibrium)
summ_14m_no_sui <- summary(DF_simulations_no_sui_14m$Equilibrium)
summ_15m_no_sui <- summary(DF_simulations_no_sui_15m$Equilibrium)
summ_16m_no_sui <- summary(DF_simulations_no_sui_16m$Equilibrium)
summ_17m_no_sui <- summary(DF_simulations_no_sui_17m$Equilibrium)
summ_18m_no_sui <- summary(DF_simulations_no_sui_18m$Equilibrium)
summ_19m_no_sui <- summary(DF_simulations_no_sui_19m$Equilibrium)
summ_20m_no_sui <- summary(DF_simulations_no_sui_20m$Equilibrium)
summ_21m_no_sui <- summary(DF_simulations_no_sui_21m$Equilibrium)

# Save csv files 
# raw simulated data
write.csv(Equilibrium_no_sui_1_manip, "No_sui_data_output/DF_no_sui_equilibrium_1_manipulated.csv")
write.csv(Equilibrium_no_sui_2_manip, "No_sui_data_output/DF_no_sui_equilibrium_2_manipulated.csv")
write.csv(Equilibrium_no_sui_3_manip, "No_sui_data_output/DF_no_sui_equilibrium_3_manipulated.csv")
write.csv(Equilibrium_no_sui_4_manip, "No_sui_data_output/DF_no_sui_equilibrium_4_manipulated.csv")
write.csv(Equilibrium_no_sui_5_manip, "No_sui_data_output/DF_no_sui_equilibrium_5_manipulated.csv")
write.csv(Equilibrium_no_sui_6_manip, "No_sui_data_output/DF_no_sui_equilibrium_6_manipulated.csv")
write.csv(Equilibrium_no_sui_7_manip, "No_sui_data_output/DF_no_sui_equilibrium_7_manipulated.csv")
write.csv(Equilibrium_no_sui_8_manip, "No_sui_data_output/DF_no_sui_equilibrium_8_manipulated.csv")
write.csv(Equilibrium_no_sui_9_manip, "No_sui_data_output/DF_no_sui_equilibrium_9_manipulated.csv")
write.csv(Equilibrium_no_sui_10_manip, "No_sui_data_output/DF_no_sui_equilibrium_10_manipulated.csv")
write.csv(Equilibrium_no_sui_11_manip, "No_sui_data_output/DF_no_sui_equilibrium_11_manipulated.csv")
write.csv(Equilibrium_no_sui_12_manip, "No_sui_data_output/DF_no_sui_equilibrium_12_manipulated.csv")
write.csv(Equilibrium_no_sui_13_manip, "No_sui_data_output/DF_no_sui_equilibrium_13_manipulated.csv")
write.csv(Equilibrium_no_sui_14_manip, "No_sui_data_output/DF_no_sui_equilibrium_14_manipulated.csv")
write.csv(Equilibrium_no_sui_15_manip, "No_sui_data_output/DF_no_sui_equilibrium_15_manipulated.csv")
write.csv(Equilibrium_no_sui_16_manip, "No_sui_data_output/DF_no_sui_equilibrium_16_manipulated.csv")
write.csv(Equilibrium_no_sui_17_manip, "No_sui_data_output/DF_no_sui_equilibrium_17_manipulated.csv")
write.csv(Equilibrium_no_sui_18_manip, "No_sui_data_output/DF_no_sui_equilibrium_18_manipulated.csv")
write.csv(Equilibrium_no_sui_19_manip, "No_sui_data_output/DF_no_sui_equilibrium_19_manipulated.csv")
write.csv(Equilibrium_no_sui_20_manip, "No_sui_data_output/DF_no_sui_equilibrium_20_manipulated.csv")
write.csv(Equilibrium_no_sui_21_manip, "No_sui_data_output/DF_no_sui_equilibrium_21_manipulated.csv")
# totals
write.csv(DF_simulations_no_sui_1m, "No_sui_data_output/DF_no_sui_simulations_1_manipulated.csv")
write.csv(DF_simulations_no_sui_2m, "No_sui_data_output/DF_no_sui_simulations_2_manipulated.csv")
write.csv(DF_simulations_no_sui_3m, "No_sui_data_output/DF_no_sui_simulations_3_manipulated.csv")
write.csv(DF_simulations_no_sui_4m, "No_sui_data_output/DF_no_sui_simulations_4_manipulated.csv")
write.csv(DF_simulations_no_sui_5m, "No_sui_data_output/DF_no_sui_simulations_5_manipulated.csv")
write.csv(DF_simulations_no_sui_6m, "No_sui_data_output/DF_no_sui_simulations_6_manipulated.csv")
write.csv(DF_simulations_no_sui_7m, "No_sui_data_output/DF_no_sui_simulations_7_manipulated.csv")
write.csv(DF_simulations_no_sui_8m, "No_sui_data_output/DF_no_sui_simulations_8_manipulated.csv")
write.csv(DF_simulations_no_sui_9m, "No_sui_data_output/DF_no_sui_simulations_9_manipulated.csv")
write.csv(DF_simulations_no_sui_10m, "No_sui_data_output/DF_no_sui_simulations_10_manipulated.csv")
write.csv(DF_simulations_no_sui_11m, "No_sui_data_output/DF_no_sui_simulations_11_manipulated.csv")
write.csv(DF_simulations_no_sui_12m, "No_sui_data_output/DF_no_sui_simulations_12_manipulated.csv")
write.csv(DF_simulations_no_sui_13m, "No_sui_data_output/DF_no_sui_simulations_13_manipulated.csv")
write.csv(DF_simulations_no_sui_14m, "No_sui_data_output/DF_no_sui_simulations_14_manipulated.csv")
write.csv(DF_simulations_no_sui_15m, "No_sui_data_output/DF_no_sui_simulations_15_manipulated.csv")
write.csv(DF_simulations_no_sui_16m, "No_sui_data_output/DF_no_sui_simulations_16_manipulated.csv")
write.csv(DF_simulations_no_sui_17m, "No_sui_data_output/DF_no_sui_simulations_17_manipulated.csv")
write.csv(DF_simulations_no_sui_18m, "No_sui_data_output/DF_no_sui_simulations_18_manipulated.csv")
write.csv(DF_simulations_no_sui_19m, "No_sui_data_output/DF_no_sui_simulations_19_manipulated.csv")
write.csv(DF_simulations_no_sui_20m, "No_sui_data_output/DF_no_sui_simulations_20_manipulated.csv")
write.csv(DF_simulations_no_sui_21m, "No_sui_data_output/DF_no_sui_simulations_21_manipulated.csv")
```

```{r NS simulations INDIVIDUAL item table descriptives}
summaries <- list(summ_1m_no_sui, summ_2m_no_sui, summ_3m_no_sui, summ_4m_no_sui, summ_5m_no_sui, summ_6m_no_sui,
                  summ_7m_no_sui, summ_8m_no_sui, summ_9m_no_sui, summ_10m_no_sui, summ_11m_no_sui, summ_12m_no_sui,
                  summ_13m_no_sui, summ_14m_no_sui, summ_15m_no_sui, summ_16m_no_sui, summ_17m_no_sui, summ_18m_no_sui,
                  summ_19m_no_sui, summ_20m_no_sui, summ_21m_no_sui)

means <- c(stateEQ_no_sui_1_manip, stateEQ_no_sui_2_manip, stateEQ_no_sui_3_manip, stateEQ_no_sui_4_manip,
           stateEQ_no_sui_5_manip, stateEQ_no_sui_6_manip, stateEQ_no_sui_7_manip, stateEQ_no_sui_8_manip,
           stateEQ_no_sui_9_manip, stateEQ_no_sui_10_manip, stateEQ_no_sui_11_manip, stateEQ_no_sui_12_manip,
           stateEQ_no_sui_13_manip, stateEQ_no_sui_14_manip, stateEQ_no_sui_15_manip, stateEQ_no_sui_16_manip,
           stateEQ_no_sui_17_manip, stateEQ_no_sui_18_manip, stateEQ_no_sui_19_manip, stateEQ_no_sui_20_manip,
           stateEQ_no_sui_21_manip)

sds <- c(stateEQ_no_sui_1_manip_sd, stateEQ_no_sui_2_manip_sd, stateEQ_no_sui_3_manip_sd, stateEQ_no_sui_4_manip_sd,
         stateEQ_no_sui_5_manip_sd, stateEQ_no_sui_6_manip_sd, stateEQ_no_sui_7_manip_sd, stateEQ_no_sui_8_manip_sd,
         stateEQ_no_sui_9_manip_sd, stateEQ_no_sui_10_manip_sd, stateEQ_no_sui_11_manip_sd, stateEQ_no_sui_12_manip_sd,
         stateEQ_no_sui_13_manip_sd, stateEQ_no_sui_14_manip_sd, stateEQ_no_sui_15_manip_sd, stateEQ_no_sui_16_manip_sd,
         stateEQ_no_sui_17_manip_sd, stateEQ_no_sui_18_manip_sd, stateEQ_no_sui_19_manip_sd, stateEQ_no_sui_20_manip_sd,
         stateEQ_no_sui_21_manip_sd)

medians <- sapply(summaries, function(x) x[3])
ranges <- sapply(summaries, function(x) x[6] - x[1])
iqr <- sapply(summaries, function(x) x[5] - x[2])
q1 <- sapply(summaries, function(x) x[2])
q3 <- sapply(summaries, function(x) x[5])

data_means_sds <- data.frame(Item = 1:21, Mean = means, SD = sds)

data_summary <- data.frame(Item = 1:21, Median = medians, Range = ranges, IQR = iqr, Q1 = q1, Q3 = q3)

table_desc_no_sui <- merge(data_means_sds, data_summary, by = "Item")

print(table_desc_no_sui)

# write.csv(table_desc_no_sui, 'table_descriptives_item_manip_no_sui.xlsx')

original_plot <- ggplot(DF_simulations_no_sui, aes(x = Equilibrium)) +
  geom_density(fill = "grey", alpha = 0.5) +
  labs(title = "Original",
       x = NULL,  
       y = NULL) +  
  theme(
    panel.background = element_rect(fill = "white"),
    panel.grid.major = element_line(color = "grey", linetype = "dashed"),
    panel.grid.minor = element_line(color = "grey", linetype = "dashed"),
    text = element_text(size = 7, family = "serif"),
    plot.title = element_text(family = "serif", size = 8, hjust = 0.5)
  )

plot_list <- list()
colors <- rainbow(21)
for (i in 1:21) {
  df_name_manipulated <- paste0("DF_simulations_no_sui_", i, "m")
  
  DF_manipulated <- get(df_name_manipulated)
  
  current_plot <- ggplot(DF_manipulated, aes(x = Equilibrium)) +
    geom_density(fill = colors[i], alpha = 0.5) +
    geom_density(data = DF_simulations_no_sui, fill = "grey", alpha = 0.5) +
    labs(title = paste("Item", i),
         x = NULL,  
         y = NULL) +  
    theme(
      panel.background = element_rect(fill = "white"),
      panel.grid.major = element_line(color = "grey", linetype = "dashed"),
      panel.grid.minor = element_line(color = "grey", linetype = "dashed"),
      text = element_text(size = 7, family = "serif"),
      plot.title = element_text(family = "serif", size = 8, hjust = 0.5)
    )
  
  plot_list[[i]] <- current_plot
}

grid.arrange(original_plot, grobs = plot_list, ncol = 7)

pdf("No_sui_data_output/Figures/No_sui_simulation_equilibrium_density.pdf", width=8.75, height=5.45)
grid.arrange(grobs = plot_list, ncol = 7)
dev.off()
```

```{r NS simulations INDIVIDUAL manipulations total}

get_variable_totals <- function(df) {
  data.frame(variable = paste0("R", 1:ncol(df)), count = colSums(df))
}

total_1m_ns <- get_variable_totals(Equilibrium_no_sui_1_manip)
total_2m_ns <- get_variable_totals(Equilibrium_no_sui_2_manip)
total_3m_ns <- get_variable_totals(Equilibrium_no_sui_3_manip)
total_4m_ns <- get_variable_totals(Equilibrium_no_sui_4_manip)
total_5m_ns <- get_variable_totals(Equilibrium_no_sui_5_manip)
total_6m_ns <- get_variable_totals(Equilibrium_no_sui_6_manip)
total_7m_ns <- get_variable_totals(Equilibrium_no_sui_7_manip)
total_8m_ns <- get_variable_totals(Equilibrium_no_sui_8_manip)
total_9m_ns <- get_variable_totals(Equilibrium_no_sui_9_manip)
total_10m_ns <- get_variable_totals(Equilibrium_no_sui_10_manip)
total_11m_ns <- get_variable_totals(Equilibrium_no_sui_11_manip)
total_12m_ns <- get_variable_totals(Equilibrium_no_sui_12_manip)
total_13m_ns <- get_variable_totals(Equilibrium_no_sui_13_manip)
total_14m_ns <- get_variable_totals(Equilibrium_no_sui_14_manip)
total_15m_ns <- get_variable_totals(Equilibrium_no_sui_15_manip)
total_16m_ns <- get_variable_totals(Equilibrium_no_sui_16_manip)
total_17m_ns <- get_variable_totals(Equilibrium_no_sui_17_manip)
total_18m_ns <- get_variable_totals(Equilibrium_no_sui_18_manip)
total_19m_ns <- get_variable_totals(Equilibrium_no_sui_19_manip)
total_20m_ns <- get_variable_totals(Equilibrium_no_sui_20_manip)
total_21m_ns <- get_variable_totals(Equilibrium_no_sui_21_manip)


total_manipulated_ns <- data.frame(
  total_1m_ns,
  total_2m_ns,
  total_3m_ns,
  total_4m_ns,
  total_5m_ns,
  total_6m_ns,
  total_7m_ns,
  total_8m_ns,
  total_9m_ns,
  total_10m_ns,
  total_11m_ns,
  total_12m_ns,
  total_13m_ns,
  total_14m_ns,
  total_15m_ns,
  total_16m_ns,
  total_17m_ns,
  total_18m_ns,
  total_19m_ns,
  total_20m_ns,
  total_21m_ns
)

print(total_manipulated_ns)

write.csv(total_manipulated_ns, 'No_sui_data_output/DF_no_sui_equilibrium_manipulated_totals.csv')
```

```{r NS individual manipulation simulation plots}
## plots at equilibrium ## 

plot_list <- list()

for (i in 1:21) {
  df_name_manipulated <- paste0("DF_simulations_no_sui_", i, "m")
  DF_manipulated <- transform(get(df_name_manipulated), Type = "Manipulated")
  
  current_plot <- ggplot(DF_manipulated, aes(x = Timepoints, y = Equilibrium)) +
    geom_line(color = "black") +  
    theme_classic() +
    labs(title = paste("Item", i), 
         x = NULL,  
         y = NULL) +  
    theme(
      plot.title = element_text(family = "serif", size = 8, hjust = 0.5),
      axis.title = element_blank(),  
      axis.text = element_text(family = "serif", size = 6),
      legend.position = "none"  
    ) +
    scale_x_continuous(breaks = c(0, 10000, 20000))

  plot_list[[i]] <- current_plot
}

grid.arrange(grobs = plot_list, ncol = 7)
```
```{r NS overlap original and manipulated (individual) equilibrium plots}

DF_simulations_no_sui_ori <- DF_simulations_no_sui[, c("Timepoints", "Equilibrium")] # original equilibrium for non-suicide group (remove perturbations colmn to match the manipulated equilibrium dataframe)

plot_list <- list()

for (i in 1:21) {
  df_name_ori <- "DF_simulations_no_sui_ori"
  df_name_manipulated <- paste0("DF_simulations_no_sui_", i, "m")
  
  DF_combined <- rbind(
    transform(get(df_name_ori), Type = "Original"),
    transform(get(df_name_manipulated), Type = "Manipulated")
  )
  
  current_plot <- ggplot(DF_combined, aes(x = Timepoints, y = Equilibrium, color = Type)) +
    geom_line() +
    scale_color_manual(values = c("#00CCFF", "#3300FF")) +  
    theme_classic() +
    labs(title = paste("Item", i), 
         x = NULL, 
         y = NULL) +  
    theme(
      plot.title = element_text(family = "serif", size = 10, hjust = 0.5),
      axis.title = element_blank(),  
      axis.text = element_text(family = "serif", size = 8),
      legend.position = "none"  
    ) +
    scale_x_continuous(breaks = c(0, 10000, 20000))
  
  plot_list[[i]] <- current_plot
}

grid.arrange(grobs = plot_list, ncol = 7)

pdf("No_sui_data_output/Figures/No_sui_simulation_equilibrium_plots.pdf", width=8.37, height=5.17)
grid.arrange(grobs = plot_list, ncol = 7)
dev.off()

pdf("No_sui_data_output/Figures/No_sui_simulation_equilibrium_ind_plots.pdf", width=8.37, height=5.17) # all time points
plot_list
dev.off()
```

```{r NS individual manipulations system activity preferences}

set.seed(123456)
l_ns_m1 <- make_2d_Isingland(thresholds = manipulated_thresholds_resst_no_sui_sim1, 
                        weiadj = RESST_no_sui_binary$weiadj, 
                        beta = 1, 
                        transform = TRUE)

plot(l_ns_m1)
calculate_resilience(l_ns_m1)


set.seed(123456)
l_ns_m2 <- make_2d_Isingland(thresholds = manipulated_thresholds_resst_no_sui_sim2, 
                        weiadj = RESST_no_sui_binary$weiadj, 
                        beta = 1, 
                        transform = TRUE)

plot(l_ns_m2)
calculate_resilience(l_ns_m2)

set.seed(123456)
l_ns_m3 <- make_2d_Isingland(thresholds = manipulated_thresholds_resst_no_sui_sim3, 
                        weiadj = RESST_no_sui_binary$weiadj, 
                        beta = 1, 
                        transform = TRUE)

plot(l_ns_m3)
calculate_resilience(l_ns_m3)


set.seed(123456)
l_ns_m4 <- make_2d_Isingland(thresholds = manipulated_thresholds_resst_no_sui_sim4, 
                        weiadj = RESST_no_sui_binary$weiadj, 
                        beta = 1, 
                        transform = TRUE)

plot(l_ns_m4)
calculate_resilience(l_ns_m4)

set.seed(123456)
l_ns_m5 <- make_2d_Isingland(thresholds = manipulated_thresholds_resst_no_sui_sim5, 
                        weiadj = RESST_no_sui_binary$weiadj, 
                        beta = 1, 
                        transform = TRUE)

plot(l_ns_m5)
calculate_resilience(l_ns_m5)


set.seed(123456)
l_ns_m6 <- make_2d_Isingland(thresholds = manipulated_thresholds_resst_no_sui_sim6, 
                        weiadj = RESST_no_sui_binary$weiadj, 
                        beta = 1, 
                        transform = TRUE)

plot(l_ns_m6)
calculate_resilience(l_ns_m6)

set.seed(123456)
l_ns_m7 <- make_2d_Isingland(thresholds = manipulated_thresholds_resst_no_sui_sim7, 
                        weiadj = RESST_no_sui_binary$weiadj, 
                        beta = 1, 
                        transform = TRUE)

plot(l_ns_m7)
calculate_resilience(l_ns_m7)


set.seed(123456)
l_ns_m8 <- make_2d_Isingland(thresholds = manipulated_thresholds_resst_no_sui_sim8, 
                        weiadj = RESST_no_sui_binary$weiadj, 
                        beta = 1, 
                        transform = TRUE)

plot(l_ns_m8)
calculate_resilience(l_ns_m8)

set.seed(123456)
l_ns_m9 <- make_2d_Isingland(thresholds = manipulated_thresholds_resst_no_sui_sim9, 
                        weiadj = RESST_no_sui_binary$weiadj, 
                        beta = 1, 
                        transform = TRUE)

plot(l_ns_m9)
calculate_resilience(l_ns_m9)


set.seed(123456)
l_ns_m10 <- make_2d_Isingland(thresholds = manipulated_thresholds_resst_no_sui_sim10, 
                        weiadj = RESST_no_sui_binary$weiadj, 
                        beta = 1, 
                        transform = TRUE)

plot(l_ns_m10)
calculate_resilience(l_ns_m10)

set.seed(123456)
l_ns_m11 <- make_2d_Isingland(thresholds = manipulated_thresholds_resst_no_sui_sim11, 
                        weiadj = RESST_no_sui_binary$weiadj, 
                        beta = 1, 
                        transform = TRUE)

plot(l_ns_m11)
calculate_resilience(l_ns_m11)


set.seed(123456)
l_ns_m12 <- make_2d_Isingland(thresholds = manipulated_thresholds_resst_no_sui_sim12, 
                        weiadj = RESST_no_sui_binary$weiadj, 
                        beta = 1, 
                        transform = TRUE)

plot(l_ns_m12)
calculate_resilience(l_ns_m12)

set.seed(123456)
l_ns_m13 <- make_2d_Isingland(thresholds = manipulated_thresholds_resst_no_sui_sim13, 
                        weiadj = RESST_no_sui_binary$weiadj, 
                        beta = 1, 
                        transform = TRUE)

plot(l_ns_m13)
calculate_resilience(l_ns_m13)


set.seed(123456)
l_ns_m14 <- make_2d_Isingland(thresholds = manipulated_thresholds_resst_no_sui_sim14, 
                        weiadj = RESST_no_sui_binary$weiadj, 
                        beta = 1, 
                        transform = TRUE)

plot(l_ns_m14)
calculate_resilience(l_ns_m14)

set.seed(123456)
l_ns_m15 <- make_2d_Isingland(thresholds = manipulated_thresholds_resst_no_sui_sim15, 
                        weiadj = RESST_no_sui_binary$weiadj, 
                        beta = 1, 
                        transform = TRUE)

plot(l_ns_m15)
calculate_resilience(l_ns_m15)


set.seed(123456)
l_ns_m16 <- make_2d_Isingland(thresholds = manipulated_thresholds_resst_no_sui_sim16, 
                        weiadj = RESST_no_sui_binary$weiadj, 
                        beta = 1, 
                        transform = TRUE)

plot(l_ns_m16)
calculate_resilience(l_ns_m16)

set.seed(123456)
l_ns_m17 <- make_2d_Isingland(thresholds = manipulated_thresholds_resst_no_sui_sim17, 
                        weiadj = RESST_no_sui_binary$weiadj, 
                        beta = 1, 
                        transform = TRUE)
plot(l_ns_m17)
calculate_resilience(l_ns_m17)

set.seed(123456)
l_ns_m18 <- make_2d_Isingland(thresholds = manipulated_thresholds_resst_no_sui_sim18, 
                        weiadj = RESST_no_sui_binary$weiadj, 
                        beta = 1, 
                        transform = TRUE)

plot(l_ns_m18)
calculate_resilience(l_ns_m18)


set.seed(123456)
l_ns_m19 <- make_2d_Isingland(thresholds = manipulated_thresholds_resst_no_sui_sim19, 
                        weiadj = RESST_no_sui_binary$weiadj, 
                        beta = 1, 
                        transform = TRUE)

plot(l_ns_m19)
calculate_resilience(l_ns_m19)

set.seed(123456)
l_ns_m20 <- make_2d_Isingland(thresholds = manipulated_thresholds_resst_no_sui_sim20, 
                        weiadj = RESST_no_sui_binary$weiadj, 
                        beta = 1, 
                        transform = TRUE)

plot(l_ns_m20)
calculate_resilience(l_ns_m20)


set.seed(123456)
l_ns_m21 <- make_2d_Isingland(thresholds = manipulated_thresholds_resst_no_sui_sim21, 
                        weiadj = RESST_no_sui_binary$weiadj, 
                        beta = 1, 
                        transform = TRUE)

plot(l_ns_m21)
calculate_resilience(l_ns_m21)


## plot all images ##

add_title_and_remove_axes_labels <- function(plot_object, title) {
  plot_object +
    ggtitle(title) +
    theme(
      axis.title.x = element_blank(),
      axis.title.y = element_blank(),
      axis.text.x = element_blank(),
      axis.text.y = element_blank(),
      plot.title = element_text(family = "serif", size = 8, hjust = 0.5)
    )
}

# 3x7 
plot_grid(
  add_title_and_remove_axes_labels(plot(l_ns_m1), "Item 1"),
  add_title_and_remove_axes_labels(plot(l_ns_m2), "Item 2"),
  add_title_and_remove_axes_labels(plot(l_ns_m3), "Item 3"),
  add_title_and_remove_axes_labels(plot(l_ns_m4), "Item 4"),
  add_title_and_remove_axes_labels(plot(l_ns_m5), "Item 5"),
  add_title_and_remove_axes_labels(plot(l_ns_m6), "Item 6"),
  add_title_and_remove_axes_labels(plot(l_ns_m7), "Item 7"),
  
  add_title_and_remove_axes_labels(plot(l_ns_m8), "Item 8"),
  add_title_and_remove_axes_labels(plot(l_ns_m9), "Item 9"),
  add_title_and_remove_axes_labels(plot(l_ns_m10), "Item 10"),
  add_title_and_remove_axes_labels(plot(l_ns_m11), "Item 11"),
  add_title_and_remove_axes_labels(plot(l_ns_m12), "Item 12"),
  add_title_and_remove_axes_labels(plot(l_ns_m13), "Item 13"),
  add_title_and_remove_axes_labels(plot(l_ns_m14), "Item 14"),
  
  add_title_and_remove_axes_labels(plot(l_ns_m15), "Item 15"),
  add_title_and_remove_axes_labels(plot(l_ns_m16), "Item 16"),
  add_title_and_remove_axes_labels(plot(l_ns_m17), "Item 17"),
  add_title_and_remove_axes_labels(plot(l_ns_m18), "Item 18"),
  add_title_and_remove_axes_labels(plot(l_ns_m19), "Item 19"),
  add_title_and_remove_axes_labels(plot(l_ns_m20), "Item 20"),
  add_title_and_remove_axes_labels(plot(l_ns_m21), "Item 21"),
  
  ncol = 7
)
```

```{r NS Ising model simulation}

input_no_sui <- list(graph = connectivity_resst_no_sui_sim, intercepts = thresholds_resst_no_sui_sim)

# network 
set.seed(123456)
Sim3 <- netSimulator(
  input = input_no_sui,
  default = "IsingFit",  
  nCases = 371,
  nReps = 1000,
  nCores = 4 
)

Sim3
```

```{r NS Model structure test}

LCT_recovery_no_sui <- LCT(
  RESST_no_sui_binary,
  corr = "auto", # tetrachoric (binary)
  model = "glasso",
  algorithm = "walktrap",
  uni.method = "Louvain", 
  iter = 100, # recommended
  seed = 123456,
  verbose = FALSE,
)

LCT_recovery_no_sui
```

### Both groups

```{r B Glauber dynamics equilibrium  totals sui and no sui}

totals_no_sui_ <- colSums(Equilibrium_no_sui) # total occurrences for each symptom non-suicide group
totals_no_sui <- get_variable_totals(Equilibrium_no_sui)


totals_sui_ <- colSums(Equilibrium_sui) # total occurrences for each symptom in suicide group
totals_sui <- get_variable_totals(Equilibrium_sui)

totals_sui_
totals_sui

df_totals_equil <- data.frame(
  Symptom = paste("R", seq_along(totals_no_sui), sep = ""),
  TotalOccurrences_No_Sui = totals_no_sui,
  TotalOccurrences_Sui = totals_sui
)

print(df_totals_equil)

write.csv(df_totals_equil, 'Both_sui_data_output/DF_sui_no_sui_equilibrium_symptom_totals.csv') # file with total number of active features for both groups

## proportion tests between group totals ##

Equilibrium_no_sui <- as.data.frame(Equilibrium_no_sui)
Equilibrium_sui <- as.data.frame(Equilibrium_sui)

proportions_data <- data.frame(Item = character(0), Proportion_No_Sui = numeric(), Proportion_Sui = numeric())

for (item in paste0('V', 1:21)) {
  
  # proportions of symptom appearances for no suicide group
  proportions_no_sui <- prop.table(table(Equilibrium_no_sui[[item]]))
  
  # proportions of symptom appearances for suicide group
  proportions_sui <- prop.table(table(Equilibrium_sui[[item]]))
  proportions_data <- rbind(proportions_data, data.frame(Item = item, Proportion_No_Sui = proportions_no_sui[2], Proportion_Sui = proportions_sui[2]))
}

print(proportions_data)
combined_totals_prop_data <- cbind(df_totals_equil, # dataframe with symptom totals per manipulated feature - made in one of the above chunks
                                   proportions_data)
print(combined_totals_prop_data)

# now calculate difference in proportions with Cohen's h

effect_sizes <- c(
  ES.h(0.55185, 0.02535),
  ES.h(0.71885, 0.11345),
  ES.h(0.85130, 0.09230),
  ES.h(0.80855, 0.13845),
  ES.h(0.71885, 0.05450),
  ES.h(0.59840, 0.11320),
  ES.h(0.60095, 0.08375),
  ES.h(0.95160, 0.14845),
  ES.h(0.96645, 0.30925),
  ES.h(0.99795, 0.43505),
  ES.h(0.21150, 0.05735),
  ES.h(0.94440, 0.24800),
  ES.h(0.98475, 0.17320),
  ES.h(0.96225, 0.16355),
  ES.h(0.99355, 0.22345),
  ES.h(0.97310, 0.18450),
  ES.h(0.97800, 0.22740),
  ES.h(0.98445, 0.50110),
  ES.h(0.97940, 0.62025),
  ES.h(0.98675, 0.63100),
  ES.h(0.91525, 0.49665)
)

effect_sizes

# function for confidence intervals for cohen h
cohens_h = function( prop_1, prop_2, n1, n2, ci = 0.95 ){
    x1 = asin(sign(prop_1) * sqrt(abs(prop_1)))
    x2 = asin(sign(prop_2) * sqrt(abs(prop_2)))
    es = x1 - x2
    se = sqrt(0.25 * (1 / n1 + 1 / n2 ))
    ci_diff = qnorm(1 - (1-ci) / 2) * se
    return( c( h = es*2, h_low = (es-ci_diff)*2, h_upp = (es+ci_diff)*2 ) )
}

effect_sizes_CIs <- c(
  cohens_h(0.55185, 0.02535, 20000, 20000),
  cohens_h(0.71885, 0.11345, 20000, 20000),
  cohens_h(0.85130, 0.09230, 20000, 20000),
  cohens_h(0.80855, 0.13845, 20000, 20000),
  cohens_h(0.71885, 0.05450, 20000, 20000),
  cohens_h(0.59840, 0.11320, 20000, 20000),
  cohens_h(0.60095, 0.08375, 20000, 20000),
  cohens_h(0.95160, 0.14845, 20000, 20000),
  cohens_h(0.96645, 0.30925, 20000, 20000),
  cohens_h(0.99795, 0.43505, 20000, 20000),
  cohens_h(0.21150, 0.05735, 20000, 20000),
  cohens_h(0.94440, 0.24800, 20000, 20000),
  cohens_h(0.98475, 0.17320, 20000, 20000),
  cohens_h(0.96225, 0.16355, 20000, 20000),
  cohens_h(0.99355, 0.22345, 20000, 20000),
  cohens_h(0.97310, 0.18450, 20000, 20000),
  cohens_h(0.97800, 0.22740, 20000, 20000),
  cohens_h(0.98445, 0.50110, 20000, 20000),
  cohens_h(0.97940, 0.62025, 20000, 20000),
  cohens_h(0.98675, 0.63100, 20000, 20000),
  cohens_h(0.91525, 0.49665, 20000, 20000)
)

print(effect_sizes_CIs)
```

```{r B Overlap original and manipulated (individual) equilibrium plots}
custom_colors <- c("#00CCFF", "#3300FF", "#663399", "#CC99FF")

plot_list <- list()

max_time_points <- 6000 # change based on visual ease

for (i in 1:21) {
  df_name_ori <- "DF_simulations_sui_ori"
  df_name_sui <- paste0("DF_simulations_sui_", i, "m")
  df_name_no_sui <- paste0("DF_simulations_no_sui_", i, "m")
  df_name_no_sui_ori <- "DF_simulations_no_sui_ori"
  
  combined_df <- rbind( # all scenarios
    transform(get(df_name_ori), Type = paste("Original")),
    transform(get(df_name_sui), Type = paste("Sui_", i, "m")),
    transform(get(df_name_no_sui), Type = paste("No_Sui_", i, "m")),
    transform(get(df_name_no_sui_ori), Type = paste("No_Sui_Original"))
  )
  
  current_plot <- ggplot(combined_df, aes(x = Timepoints, y = Equilibrium, color = Type)) +
    geom_line() +
    scale_color_manual(values = custom_colors) +  
    theme_classic() +
    labs(title = paste("Item", i),
         x = NULL,  
         y = NULL) +  
    theme(
      plot.title = element_text(family = "serif", size = 12, hjust = 0.5),
      axis.title = element_blank(), 
      axis.text = element_text(family = "serif", size = 10),
      legend.position = "none"  
    ) +
    scale_x_continuous(breaks = c(0, 10000, 20000), limits = c(0, max_time_points))
  
  plot_list[[i]] <- current_plot
}

grid.arrange(grobs = plot_list, ncol = 7)

pdf("Both_sui_data_output/Figures/Both_simulation_equilibrium_plots.pdf", width=8.37, height=5.17)
grid.arrange(grobs = plot_list, ncol = 7)
dev.off()

pdf("Both_sui_data_output/Figures/Both_simulation_equilibrium_ind_plots.pdf", width=8.37, height=5.17) # all time points
plot_list
dev.off()
```


```{r B Overlap original and manipulated (individual) equilibrium boxplots}
pdf("Both_sui_data_output/Figures/Both_simulation_equilibrium_ind_boxplots.pdf", width=8.37, height=5.17) 

colors <- c("#00CCFF", "#CC99FF", "#3300FF", "#663399")

for (i in 1:21) {

  my_data_frames <- list()

  for (j in c("m_ns", "m_s")) {
    
    df_name <- paste0("total_", i, j)

    if (exists(df_name)) {

      my_data_frames[[df_name]] <- get(df_name)
      my_data_frames[[df_name]]$Scenario <- df_name
    }
  }

  for (additional_scenario in c("totals_sui", "totals_no_sui")) {
    
    df_name <- paste0(additional_scenario)

    if (exists(df_name)) {
     
      my_data_frames[[df_name]] <- get(df_name)
      my_data_frames[[df_name]]$Scenario <- df_name
    }
  }

  combined_df <- do.call(rbind, my_data_frames)

  plot_title <- paste("Item", i)
  p <- ggplot(combined_df, aes(x = factor(Scenario), y = count, fill = Scenario)) +
    geom_boxplot() +
    labs(title = plot_title,
         x = NULL,  
         y = NULL) + 
    scale_fill_manual(values = colors) +  
    scale_x_discrete(labels = setNames(c("S total", "NS total", paste0("S ", i, " total"), paste0("NS ", i, " total")),
                                      c("totals_sui", "totals_no_sui", paste0("total_", i, "m_s"), paste0("total_", i, "m_ns")))) +  
    theme_minimal() +
    theme(
      plot.title = element_text(family = "serif", size = 10, hjust = 0.5),
      axis.title = element_blank(), 
      axis.text = element_text(family = "serif", size = 8),
      legend.position = "none"
    )
  
  print(p)
}

dev.off()

## all in one ##
plot_list <- list()

for (i in 1:21) {

  my_data_frames <- list()

  for (j in c("m_ns", "m_s")) {
    
    df_name <- paste0("total_", i, j)

    if (exists(df_name)) {

      my_data_frames[[df_name]] <- get(df_name)
      my_data_frames[[df_name]]$Scenario <- df_name
    }
  }

  for (additional_scenario in c("totals_sui", "totals_no_sui")) {
    
    df_name <- paste0(additional_scenario)

    if (exists(df_name)) {
     
      my_data_frames[[df_name]] <- get(df_name)
      my_data_frames[[df_name]]$Scenario <- df_name
    }
  }

  combined_df <- do.call(rbind, my_data_frames)

  plot_title <- paste("Item", i)
  
  # Define custom labels inside the loop
  custom_labels <- setNames(c("S total", "NS total", paste0("S ", i, " total"), paste0("NS ", i, " total")),
                            c("totals_sui", "totals_no_sui", paste0("total_", i, "m_s"), paste0("total_", i, "m_ns")))

  p <- ggplot(combined_df, aes(x = factor(Scenario), y = count, fill = Scenario)) +
    geom_boxplot() +
    labs(title = plot_title,
         x = NULL,  
         y = NULL) + 
    scale_fill_manual(values = colors) +  
    scale_x_discrete(labels = custom_labels) +  
    theme_minimal() +
    theme(
      plot.title = element_text(family = "serif", size = 8, hjust = 0.5),
      axis.title = element_blank(), 
      axis.text = element_text(family = "serif", size = 6),
      axis.text.x = element_blank(),  
      axis.text.y = element_blank(), 
      legend.position = "none"
    )
  
  plot_list[[i]] <- p
}

grid.arrange(grobs = plot_list, ncol = 7)

pdf("Both_sui_data_output/Figures/Both_simulation_equilibrium_boxplots.pdf", width=8.37, height=5.17) 
grid.arrange(grobs = plot_list, ncol = 7)
dev.off()
```